### ISSUE TITLE
Improve in Nav bar section for good design 

### ISSUE THREAD

**Issue by justynigam** [Anjaliavv51/Retro#10]
I can make a good nav bar which can be helpful for see nav bar section if any white background or blackground comes it can be visible
can u assign me in this issue?
im from Gssoc contributer.

**Comment by Ananya-vastare** [comment]
Can you please assign me to this I am a GSSOC contributor

**Comment by Anjaliavv51** [comment]
@justynigam please explain the issue clearly with Screenshoot.

**Comment by justynigam** [comment]
![Screenshot 2024-10-01 213106](https://github.com/user-attachments/assets/8eff7ebc-7b2e-4b18-9c5e-7cea3cb93ad5)
here the nav bar is transparent 
sometimes making multiple page can make issue to see clearly what is written in nav because it is transparent if we can make little blur with nav bar background then it can be more visible

**Comment by Anjaliavv51** [comment]
@justynigam go ahead!

**Comment by Sanikaaher-19** [comment]
Update Navbar from Transparent to Visible
fixes https://github.com/Anjaliavv51/Retro/issues/10

Updates the navbar from a transparent background to a visible one, improving the overall user experience and readability of the navigation menu.

Changes:
Modified the navbar background from transparent to a visible color, making it more prominent and easier to use.

retro redesign navbar

**Comment by Sanikaaher-19** [comment]
![retro redesign navbar](https://github.com/user-attachments/assets/91a49cea-854f-4ad8-af08-3ef19090d987)

**Comment by justynigam** [comment]
@Anjaliavv51 successfully done , 
check #44 if any issue i will solve it
