### ISSUE TITLE
🐞[bug]: hover effect in footer section

### ISSUE THREAD

**Issue by bhumikasinhaB** [Anjaliavv51/Retro#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i want to add hover effect in the footer section of social media link ( follow us ) to make it more user-friendly .The goal is to create a cohesive retro aesthetic with vintage-style fonts, colors .Hover effects on links and buttons will be added for interactivity, using subtle animations that reflect a retro vibe, such as pixelated transitions or glowing text.

### Expected behavior

I wanted that when I click the icons on follow us section they should slightly pop up and hover with coordinating background colour. 

### Add ScreenShots

![Screenshot (3)](https://github.com/user-attachments/assets/66bafc20-ce4c-4b39-8f32-4460a52cc2aa)
the (Follow Us) section.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@bhumikasinhaB it is already done , please check it.

**Comment by Anjaliavv51** [comment]
And also I am closing this issue as completed.
