### ISSUE TITLE
FACING MERGE ISSUE!!!

### ISSUE THREAD

**Issue by laxmikandivalasa** [Anjaliavv51/Retro#101]
![Screenshot 2024-10-02 224045](https://github.com/user-attachments/assets/5aab82bd-c0a9-44da-bfb0-7453a44b5b3f)
hey @Anjaliavv51 I've committed and sent pr for this Repo...
but I'm facing issue as it is not showing in github page->pull requests
when i check my git status it shows everything up to date
can you whats wrong with this!!

**Comment by Anjaliavv51** [comment]
join this meet

https://meet.google.com/wyv-wuwh-yci

**Comment by Anjaliavv51** [comment]
@laxmi47
