### ISSUE TITLE
🐞[bug]: Ensure Consistent Card Height for Better Presentation.

### ISSUE THREAD

**Issue by grasyPatel** [Anjaliavv51/Retro#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The cards on the [ homepage page] have varying heights, which disrupts the visual consistency of the layout. This inconsistency can affect the overall user experience and presentation of the website.
The cards have different heights due to varying amounts of content, such as images, text, or other elements. This creates an uneven appearance, especially when multiple cards are displayed side by side.

### Expected behavior

All cards should have a uniform height, regardless of their content. This would provide a more organized and professional appearance, improving the overall user experience.

### Add ScreenShots

<img width="1431" alt="Screenshot 2024-10-02 at 11 23 58 PM" src="https://github.com/user-attachments/assets/a1803af6-0a11-48af-b363-297cc3a8f487">

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@grasyPatel so ahead.
