### ISSUE TITLE
🐞[bug]: Images, text size & color, padding problems.

### ISSUE THREAD

**Issue by akansha-02** [Anjaliavv51/Retro#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text size is very small and its color is very light causing visibility problem for a mobile user.
The background image is not properly aligned.
The padding for text area for contact details is not correctly defined.
The button used is not much appealing for the website.

Please assign me these issues  under gssoc'24 EXTENDED and hacktoberfest.

### Expected behavior

The Heading of the page can be highlighted in order to distinguish it from the other texts.
The images can be aligned as centre to make the page more responsive.

### Add ScreenShots

![Screenshot 2024-10-03 001430](https://github.com/user-attachments/assets/653b87fc-7fae-43b1-85e0-b3458c4df79f)
![Screenshot 2024-10-03 001442](https://github.com/user-attachments/assets/fafc8906-a03c-4467-936a-8cf5a1607816)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by akansha-02** [comment]
Thank you for assigning me these issues. Also could you please add the level.

**Comment by Anjaliavv51** [comment]
@akansha-02 i will add it to the PR.

**Comment by Deepthi-Ramineni** [comment]
Is this issue assigned? But it shows that no one is assigned. If not, can you please assign it to me? I would like to work on it.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by Shantanu675** [comment]
Would you assign this project to me under gssoc-ext . I will try to add it PR
