### ISSUE TITLE
✨[feature Request]: Redesign Contact Us Page

### ISSUE THREAD

**Issue by amankumarcu** [Anjaliavv51/Retro#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

more interactive and visually appealing contact us page.

### Use Case

old design :-
![destroyed](https://github.com/user-attachments/assets/3117c61f-b47f-4352-afad-c07cdb18a33c)
new design :- (but with same orange bg)
<img width="432" alt="Screenshot 2024-10-03 at 1 05 53 AM" src="https://github.com/user-attachments/assets/ada0a84b-ea88-4f97-9d27-db4dc3f14f98">

### Benefits

more interactive and visually appealing contact us page.

### Add ScreenShots

old design :-
![destroyed](https://github.com/user-attachments/assets/3117c61f-b47f-4352-afad-c07cdb18a33c)
new design :- (but with same orange bg)
<img width="432" alt="Screenshot 2024-10-03 at 1 05 53 AM" src="https://github.com/user-attachments/assets/ada0a84b-ea88-4f97-9d27-db4dc3f14f98">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by amankumarcu** [comment]
@Anjaliavv51 assign it to me

**Comment by Anjaliavv51** [comment]
@amankumarcu I will assign the issue as navbar is going to be updated , pls make the changes according to that.

**Comment by amankumarcu** [comment]
i will not commit any change to navbar, just the contact us page. is it okay?

**Comment by Anjaliavv51** [comment]
`Okay`

**Comment by tulikaa25** [comment]
I would like to improve the Contact Us form with proper spacing, padding and margin utilities and create a responsive form as presently it's not responsive on all screen sizes. Please assign this issue to me @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@tulikaa25 better raise some other issue , as the current issue is already assigned to amankumar.

**Comment by amankumarcu** [comment]
who destroyed this page 👎 
![destroyed](https://github.com/user-attachments/assets/3117c61f-b47f-4352-afad-c07cdb18a33c)

**Comment by Anjaliavv51** [comment]
Let me just check.

**Comment by Anjaliavv51** [comment]
Let me just check.

**Comment by Anjaliavv51** [comment]
@amankumarcu please create an issue and solve it , please raise the issue fastly I will assign u.

**Comment by amankumarcu** [comment]
ok @Anjaliavv51 in the meanwhile merge this #141  merge this PR.

**Comment by amankumarcu** [comment]
should i close this issue and create new @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@amankumarcu just edit this issue. In detailed.

**Comment by amankumarcu** [comment]
done @Anjaliavv51

**Comment by amankumarcu** [comment]
will work on this tomorrow @Anjaliavv51

**Comment by Anjaliavv51** [comment]
> will work on this tomorrow @Anjaliavv51

Okay

**Comment by amankumarcu** [comment]
@Anjaliavv51 should i make a PR?
## New Design for Contact Us Page
<video src="https://github.com/user-attachments/assets/e1c38058-bf85-4deb-94c2-36217b8dfc4f"></video>
