### ISSUE TITLE
🐞[bug]: About section contain collections instead of about the website

### ISSUE THREAD

**Issue by iAmDiksha** [Anjaliavv51/Retro#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "About" section currently displays content related to collections instead of providing information about the website itself. This creates confusion for users who expect to find details about the site’s purpose, mission, and values.

### Expected behavior

The "About" section should contain information specifically about the website, including its objectives and what users can expect.
 
One solution can be instead of writing About, write Collections in the navbar, and create a separate section for About page later.

### Add ScreenShots

This is shown when clicking on the About in the Navbar.
<img width="955" alt="image" src="https://github.com/user-attachments/assets/72f8a522-9116-47ae-bccd-d5e655bb567f">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@iAmDiksha please create new about.html page with same navbar and footer.
And also the about page name is going to be renamed as collection's.

**Comment by Anjaliavv51** [comment]
#171
