### ISSUE TITLE
✨[feature Request]: hero section text colour change

### ISSUE THREAD

**Issue by amankumarcu** [Anjaliavv51/Retro#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Original
before changing colour to white (not visible) :- 
<img width="1439" alt="Screenshot 2024-10-03 at 1 14 23 AM" src="https://github.com/user-attachments/assets/5cd74f3a-5358-41fa-ba1f-6b768550f5be">

## Suggested Change
after changing colour to white (visible) :-
<img width="1440" alt="Screenshot 2024-10-03 at 1 14 06 AM" src="https://github.com/user-attachments/assets/b175848d-bdfb-43e4-b585-03fd823f3902">

### Use Case

visually appealing 

### Benefits

grab the viewers attention on the hero section.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by amankumarcu** [comment]
@Anjaliavv51 assign this to me as well.

**Comment by Anjaliavv51** [comment]
@amankumarcu also check total repo's files color's.

**Comment by amankumarcu** [comment]
okay sure

**Comment by vartika-dhochak2158** [comment]
@Anjaliavv51 Can you assign this issue to me as well.
