### ISSUE TITLE
🐞[bug]: the header and then the body text is not visible in the page ! and then the text which is placed under the welcome tag is not visible too , i can change that issues , and i can add a superb feature for that 

### ISSUE THREAD

**Issue by Kameshnic** [Anjaliavv51/Retro#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I hope you're doing well. I’ve noticed that there’s a visibility issue on the page:

The header and body text are not visible.
The text under the welcome tag is also hidden.
I’d like to help resolve this bug by making these elements clearly visible. Additionally, I have an idea to enhance the page with a superb feature that will improve the overall user experience.

Could you please assign this task to me? I’m excited to contribute and make meaningful changes to the project.

Looking forward to your approval!
![Screenshot 2024-10-03 120602](https://github.com/user-attachments/assets/02f172a6-4b45-4873-8f76-cbd5ca48b42c)

### Expected behavior

Expected Behavior:

I expected the header, body text, and the text under the welcome tag to be clearly visible on the page, regardless of the theme or mode (e.g., light mode, dark mode). The text should be easy to read with proper contrast against the background, ensuring a seamless user experience.

### Add ScreenShots

![Screenshot 2024-10-03 120602](https://github.com/user-attachments/assets/bfcfa0a8-ad1a-4af8-86a5-667ad8ed715d)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Kameshnic navbar is going to be updated , please raise some other issue.
