### ISSUE TITLE
🐞[bug]: Fixing twitter icon animation on service.html page

### ISSUE THREAD

**Issue by Dhruv7055** [Anjaliavv51/Retro#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Actually there is a bug in footer section of service.html page. The twitter icon animation is not working on hovering, like color is not changing on hovering twitter icon.

### Expected behavior

On hovering twitter icon the color should change to blue.

### Add ScreenShots

![Screenshot (316)](https://github.com/user-attachments/assets/23667c86-9141-4a8e-b0f8-bb2961b587b1)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Dhruv7055 currently not required please create some other issue.
