### ISSUE TITLE
I would like to format the contact us page better

### ISSUE THREAD

**Issue by harbakshsinghbaath** [Anjaliavv51/Retro#13]
the page though serves it purpose stands out of the rest of the website as it looks like it has been done in a rush I would like to make it look more polished whilst maintaining the theme of the website
<img width="947" alt="image" src="https://github.com/user-attachments/assets/1a877dc4-279a-4058-b054-6b1eb2ea9b03">

**Comment by Anjaliavv51** [comment]
@harbakshsinghbaath please add preview video of ur updated cintact us page.

**Comment by harbakshsinghbaath** [comment]
Preview video? Can't you just assign it to me so I can make it and then just check if it's any good

**Comment by Anjaliavv51** [comment]
@harbakshsinghbaath go ahead!

**Comment by Anjaliavv51** [comment]
According to the changes i will add the level label to the PR.

**Comment by harbakshsinghbaath** [comment]
Thank you

**Comment by harbakshsinghbaath** [comment]
Just wanted to add that the label is gssoc-extd they won't accept anything else

**Comment by Anjaliavv51** [comment]
> Just wanted to add that the label is gssoc-extd they won't accept anything else

that is neccessary for only PR , if label is not added to PR then u need to worry

**Comment by Anjaliavv51** [comment]
@harbakshsinghbaath any progress?

**Comment by harbakshsinghbaath** [comment]
yes almost there, i got sick this morning so sorry for the delay

**Comment by harbakshsinghbaath** [comment]
actually sorry for this but i dont think I can submit on time I'm really not doing well

**Comment by harbakshsinghbaath** [comment]
you can assign it to someone else if you want to

**Comment by Anjaliavv51** [comment]
> you can assign it to someone else if you want to

No worries , do contribute when u r fine.

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj look at this issue.

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj look at this issue.

Can u please assign to me so that I can try it with full efforts!

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj go ahead.

**Comment by Shekhar-Raj** [comment]
@Anjaliavv51 , I Have a doubt I committed the issue in my old branch and when I am creating a pull request it shows me to assign a new issue first, how can I contribute to this issue? Can u please help?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 , I Have a doubt I committed the issue in my old branch and when I am creating a pull request it shows me to assign a new issue first, how can I contribute to this issue? Can u please help?

I didn't get u place a screenshot and explain me the issue
