### ISSUE TITLE
🐞[bug]: Social media links not working on clicking of cart page

### ISSUE THREAD

**Issue by Dhruv7055** [Anjaliavv51/Retro#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Social media links not working on clicking in footer section of cart page.

### Expected behavior

If we click on facebook icon then it should be redirected to facebook page and so on.

### Add ScreenShots

![Screenshot (320)](https://github.com/user-attachments/assets/adb9258b-7aeb-4ead-8797-fa3cf0ce88bb)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by TanishSen** [comment]
I want to work on this issue please assign me.

**Comment by WednesdaySP** [comment]
@Anjaliavv51  I have already fixed this issue and made a PR please check
