### ISSUE TITLE
🐞[bug]: Home button link not working from cart page

### ISSUE THREAD

**Issue by Vaibhav-Kumar10** [Anjaliavv51/Retro#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After going to cart page, if you click the home page button, the link doesn't work.

### Expected behavior

When clicked, it should lead to the home page.

### Add ScreenShots

![Screenshot 2024-10-03 160231](https://github.com/user-attachments/assets/bc47865f-dc22-4d44-8c55-328d22c9adf4)
![Screenshot 2024-10-03 160216](https://github.com/user-attachments/assets/545c00ce-86cf-4666-9468-0f74646539a5)

https://github.com/user-attachments/assets/bd752969-9e4a-4591-97ee-b4c7604743dc

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Vaibhav-Kumar10** [comment]
Please assign me this issue for Hacktober fest and GSSoCEXTD 2024

**Comment by Vaibhav-Kumar10** [comment]
@Anjaliavv51 please help me to modify my PR so that it can be merged

**Comment by Anjaliavv51** [comment]
@Vaibhav-Kumar10 what's the issue u r facing?

**Comment by Vaibhav-Kumar10** [comment]
> @Vaibhav-Kumar10 what's the issue u r facing?

I am not able to understand why my PR was not merged

**Comment by Anjaliavv51** [comment]
@Vaibhav-Kumar10 your branch is not updated and I am unable to find the changes , so closed the PR , create another PR.

**Comment by Vaibhav-Kumar10** [comment]
> @Vaibhav-Kumar10 your branch is not updated and I am unable to find the changes , so closed the PR , create another PR.

Done.
Please confirm now.
