### ISSUE TITLE
🐞[bug]: The text is not visible on the main home page

### ISSUE THREAD

**Issue by ahinagangopadhyay** [Anjaliavv51/Retro#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text on the main home page is not visible due to light font colour.

### Expected behavior

I want to change the font colour and make the text readable.
Please assign me this issue under GSSOC Extended 2024 and Hacktoberfest 2024.

### Add ScreenShots

![Screenshot (254)](https://github.com/user-attachments/assets/82f5a7fb-58a1-4239-a9a8-34d8a3149899)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
Not required for now raise another issue
