### ISSUE TITLE
Add functionality to contact us page

### ISSUE THREAD

**Issue by ananyag309** [Anjaliavv51/Retro#14]
I would like to add functionality to contact us page - it will accept response and display the confirmation message

**Comment by AyutheCoder** [comment]
I would like to add functionality to contact us page with social media linking

**Comment by Anjaliavv51** [comment]
@ananyag309 go ahead

**Comment by ananyag309** [comment]
@Anjaliavv51 maam please add gssoc and hacktoberfest both label

**Comment by ruchikakengal** [comment]
I like To work on contact us page which i give nice ui design to the webpage . assign me

**Comment by Codersweta7** [comment]
@Anjaliavv51 please assign this issue to me

**Comment by Anjaliavv51** [comment]
No update.
