### ISSUE TITLE
Linking Of Navbar to all other pages for user-friendly website

### ISSUE THREAD

**Issue by sejals23** [Anjaliavv51/Retro#144]
Linking the navigation bar (navbar) to all other pages is a crucial aspect of creating a user-friendly website. It allows visitors to easily access different sections of the site from anywhere, enhancing the overall navigation experience. A well-linked navbar ensures that users can move seamlessly between pages without getting lost or having to repeatedly return to the homepage.

**Comment by N4171k** [comment]
hello @sejals23 happy to help on the issue !

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..
