### ISSUE TITLE
Enhancing the login and sign up Button 

### ISSUE THREAD

**Issue by sejals23** [Anjaliavv51/Retro#145]
Enhancing buttons on a web page improves both the aesthetics and user experience. Well-designed buttons are visually appealing, making them more noticeable and inviting users to take action. Enhancements such as using contrasting colors, clear text labels, appropriate sizing, and hover effects ensure that buttons stand out and are easy to interact with.

**Comment by KartikSaxena19** [comment]
you can assign this task to me
