### ISSUE TITLE
🐞[bug]: Contact page is not properly aligned

### ISSUE THREAD

**Issue by anuza08** [Anjaliavv51/Retro#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the contact page is not properly aligned 

### Expected behavior

the contact page must look aligned and readable

### Add ScreenShots

![{272E9520-7C21-4D1F-9C5A-AF7F0D37D6A7}](https://github.com/user-attachments/assets/248fdf3d-e28a-4873-9b05-ff7f5c368ee9)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by amankumarcu** [comment]
#108 im already working on this. don't make existing issues and pl check them before creating a new issue 

ps: @Anjaliavv51 close it

**Comment by amankumarcu** [comment]
close this issue @anuza08
