### ISSUE TITLE
✨[feature Request]: enhance font and navigation bar

### ISSUE THREAD

**Issue by Ishita-Si** [Anjaliavv51/Retro#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

with new better font for the nav bar it would look more attractive and replacing several buttons on the it with appropriate spacing . 

### Use Case

would make a better first impression. along with improve user interaction.

### Benefits

you would find it more easier to navigate through it .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Ishita-Si send a preview screenshot or screen recording of your idea.

**Comment by Ishita-Si** [comment]
@Anjaliavv51 Like this something with proper spacing and appropriate size of text and colour.



![maxresdefault.jpg](https://github.com/user-attachments/assets/1e1de3f4-3c17-425b-9d51-85a39c729088)

**Comment by Anjaliavv51** [comment]
@Ishita-Si not required.
