### ISSUE TITLE
✨[feature Request]: Enhance Login Page UI for Improved User Experience and Responsiveness

### ISSUE THREAD

**Issue by Sunilkumarchavhan9** [Anjaliavv51/Retro#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improved Button Design: Enhancing the buttons with a more vibrant color scheme, hover effects, and transitions will make them more visually appealing and provide better user feedback.
Dynamic Form Styling: Adding smooth transitions to form fields (like focusing on input borders and improving placeholder contrast) can help guide the user’s attention.
Responsive and Mobile-Friendly Layout: Ensuring the design is fully responsive for smaller screens to improve usability across devices.
Visual Depth with Shadows and Spacing: Introducing box shadows, text shadows, and consistent spacing to create a modern, clean look that improves the hierarchy and readability of the UI.
Engaging Background: Replacing a static background with a more appealing gradient or pattern makes the page more inviting without distracting the user.

### Use Case

As a user, I want the buttons on the login page to clearly stand out and be visually inviting to click, so I feel encouraged to complete the login/signup process.
As a user, I want to see clear focus indicators when I interact with input fields, so I can easily see where I am typing, reducing the chance of errors.
As a user, I want the login page to work well on all devices, including mobile and tablet, so I can access the page anywhere with ease.
As a developer, I want to implement a UI that enhances user interaction and feedback, ensuring users can navigate the page easily.

### Benefits

Enhanced User Engagement: The improved button design and feedback (hover effects, animations) make interactions more enjoyable, encouraging users to proceed with login or signup.
Better User Experience: Dynamic form interactions, like focus state and smooth transitions, improve the form’s usability and reduce user input errors.
Increased Mobile Usability: A fully responsive layout ensures that users on mobile devices have a seamless experience, potentially increasing conversions or registrations on smaller screens.
Modern and Professional Look: Introducing modern UI elements, like shadows and smooth transitions, makes the design look up-to-date and professional, improving user trust and brand perception.
Higher Conversion Rates: A visually engaging, responsive, and user-friendly login page encourages more users to complete the signup/login process, reducing bounce rates and increasing conversions.

### Add ScreenShots

![Screenshot 2024-10-04 001038](https://github.com/user-attachments/assets/37e62ea6-e107-4232-b59e-a3a8d51fba2e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Sunilkumarchavhan9** [comment]
I am adding these changes in rp check it out

**Comment by Anjaliavv51** [comment]
@Sunilkumarchavhan9 send screenshot or screen recording of ur changes

**Comment by Sunilkumarchavhan9** [comment]
I forgot that to mention the screen shot in issue so I updated

**Comment by Sunilkumarchavhan9** [comment]
@Anjaliavv5 i am pushed from vs code here my pr not showing what do now u have idea how to resolve
