### ISSUE TITLE
🐞[bug]: the about button in nav bar is redirecting to menu page 

### ISSUE THREAD

**Issue by Kratik1093** [Anjaliavv51/Retro#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when clicked on about in the nav bar it is redirecting to menu page insted of about page 

### Expected behavior

it should direct to about page

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@rahulgithub-web pls place screen recording of the issue.

**Comment by rahulgithub-web** [comment]
@Anjaliavv51 after clicking on `About` button in nav bar is redirecting to menu page


https://github.com/user-attachments/assets/b76850cc-e4a4-41f8-893e-9e693aa12fb5

**Comment by Anjaliavv51** [comment]
@rahulgithub-web it is being rectified.
