### ISSUE TITLE
✨[feature Request]: hover of the menu page does not looks good ith has hich chances of improvement

### ISSUE THREAD

**Issue by Kratik1093** [Anjaliavv51/Retro#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hover makes the website looks more attractive and intractive  it needs to be smooth and effective

### Use Case

make the website more intractive

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Kratik1093 place screenshot of your feature.

**Comment by Kratik1093** [comment]
![Screenshot 2024-10-04 163644](https://github.com/user-attachments/assets/2abdff43-69d1-4a0d-b5e7-d20536dc4e9c)
![Screenshot 2024-10-04 163706](https://github.com/user-attachments/assets/77051552-5b4b-479b-8d82-418564991d9f)


the menu items looks as no changes is made with hover
only the border colour changes which does not look good

**Comment by Anjaliavv51** [comment]
Go ahead.
