### ISSUE TITLE
🐞[bug]: Contact Page UI and Form Layout Disordered

### ISSUE THREAD

**Issue by grasyPatel** [Anjaliavv51/Retro#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The UI of the contact page is broken. The contact form, navigation bar, and other elements are disorganized and overlapping. This issue affects both the desktop and mobile views, leading to a poor user experience.
### Issue Details:
- **Navbar**: The navigation bar is not properly aligned and overlaps with the form.
- **Form**: The contact form fields are disordered and overlapping each other and other elements.
- **General UI**: The entire layout of the page is mixed up, with elements not adhering to the grid or proper positioning.

### Expected behavior

The contact form should be neatly aligned with no overlapping elements.
 The navigation bar should be separate from the form and positioned correctly.

### Add ScreenShots

<img width="1470" alt="Screenshot 2024-10-04 at 12 55 49 AM" src="https://github.com/user-attachments/assets/33f92499-6d20-4f47-bcf7-abd40a481bd7">

### What browsers are you seeing the problem on?

Chrome, Safari

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by grasyPatel** [comment]
@Anjaliavv51 I would like to work on fixing this issue. Could you please assign it to me?

**Comment by Anjaliavv51** [comment]
@grasyPatel please go ahead.

**Comment by Anjaliavv51** [comment]
@grasyPatel make sure font family of headings and paragraph matches the webpages fonts.
