### ISSUE TITLE
Changing position of the button in the collection section of home screen

### ISSUE THREAD

**Issue by shivamv003** [Anjaliavv51/Retro#163]
![image](https://github.com/user-attachments/assets/adadfd1c-a42b-4d7a-906c-2fa6680abfb3)

here the button and the text above the button should come in the below of the card to look more good 
opening button above the cards give the wrong impact .
i want to work on it and fix this.

please assign me this under the gssoc

**Comment by Anjaliavv51** [comment]
Not required
