### ISSUE TITLE
improving the complete alignment of the contact page

### ISSUE THREAD

**Issue by shivamv003** [Anjaliavv51/Retro#164]
The contact page of this website is not up to the mark as all its container are shrinked and appered as an coloumn like structure where every button shapes have been changed .
i want to improve this page.
![image](https://github.com/user-attachments/assets/c5f83021-59b1-45db-b7e2-e50891f290e5)

kindly assign me this under gssoc

**Comment by Anjaliavv51** [comment]
Already assigned
