### ISSUE TITLE
✨[feature Request]: Adding icons on services page.

### ISSUE THREAD

**Issue by Vaishh18** [Anjaliavv51/Retro#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On the Services page, there is a significant amount of blank space on the cards for the "Take Experience," "Book Now," and "Take Subscription" sections. 

### Use Case

Filling up blank spaces with meaningful visuals (icons).
Improving readability and overall design by aligning the contact us section.
Making the page feel more polished and professional.

### Benefits

Better User Experience (UX): Reducing empty space and improving alignment will make the page easier to navigate and visually appealing.
Clarity: Icons will quickly convey the purpose of each card to users, improving usability.

### Add ScreenShots

![retroissue](https://github.com/user-attachments/assets/4b190ddd-f540-4e1e-8cba-8c512535f4e3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Vaishh18** [comment]
@Anjaliavv51 Please assign me this issue,I would love to work on it.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by Vaishh18** [comment]
hey @Anjaliavv51 i added this icons please take a look 
![Screenshot (1059)](https://github.com/user-attachments/assets/d40484c4-09cc-48bf-8c55-26e7212339ce)
Is it ok? ,Please assign this issue to me.

**Comment by Anjaliavv51** [comment]
@Vaishh18 go ahead.
