### ISSUE TITLE
📝[documentation Update]: Add Zoom Effect to Images with Class .menu on Hover

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [Anjaliavv51/Retro#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

To enhance the user experience, improve the UI of the image display on the collection page by adding a hover effect.
![Screenshot 2024-10-04 161028](https://github.com/user-attachments/assets/904f970d-815c-4484-b526-b18072a76ca3)

### Suggested Change

Currently, the images with the class .menu do not have any interactive effect when hovered over. To improve the user experience and visual appeal, I suggest adding a zoom effect to these images when a user hovers over them.

Please consider this issue under the GSSoC 2024 Extended and Hacktoberfest Accepted tags.
Thank you!

![Screenshot 2024-10-04 160542](https://github.com/user-attachments/assets/c0f4139f-86dc-42bc-b1b6-5b9eee629616)

### Rationale

To increase the user experience while buying any thing

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@harshpareshbhaigosalya go ahead.

**Comment by KrishnaMohanty08** [comment]
@Anjaliavv51 I would like to work on this issue if they are inactive could you please assign me the task

**Comment by harshpareshbhaigosalya** [comment]
Thank you @Anjaliavv51 for assigning
