### ISSUE TITLE
Image are not visible

### ISSUE THREAD

**Issue by amanver45** [Anjaliavv51/Retro#18]
![Screenshot 2024-10-01 215125](https://github.com/user-attachments/assets/2d7f2798-f9a2-4f9d-ac01-c09959ce2bf4)

**Comment by amanver45** [comment]
Hey @Anjaliavv51 ,I can fix this issue.

**Comment by Anjaliavv51** [comment]
@amanver45 go ahead.

**Comment by Ananya-vastare** [comment]
@Anjaliavv51 I can fix this issue

**Comment by Anjaliavv51** [comment]
@amanver45 any update?
