### ISSUE TITLE
✨[feature Request]:  Include Phone Icon for Contact

### ISSUE THREAD

**Issue by Bhoomysingh10** [Anjaliavv51/Retro#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Phone Icon for Quick Contact Access
I suggest adding a phone icon to the contact page for easier access to our contact info. This would enhance user experience by simplifying communication and promoting quick engagement. Thank you for considering this!

### Use Case

1) Enhanced Engagement & User-Friendly: The phone icon encourages direct support interactions and simplifies communication through a pop-up for emails and messages.
2) Faster Responses & Centralized Tracking: Structured messaging allows quick prioritization of inquiries while ensuring no messages are lost.
3) Easy Access: Users can easily submit inquiries without phone calls or searching for contact info.

### Benefits
1) Enhanced Communication: Users can quickly reach out for assistance without leaving the page, enabling real-time interactions for immediate concerns.
2) Improved User Experience: The intuitive phone icon makes it easy for users to initiate contact, while the pop-up preserves their flow on the site.
3) Increased Engagement: A visible contact option invites user feedback and suggestions, fostering a sense of community when inquiries are acknowledged.
4) Improved Customer Satisfaction: Easy communication leads to quicker response times, and promptly addressing needs enhances overall satisfaction.
5) Adaptability: The customizable pop-up allows tailored fields for better inquiry categorization, ensuring the feature can adapt to future needs and enhancements.

### Add ScreenShots

icon:
![image](https://github.com/user-attachments/assets/7270e4f6-01ee-4941-a921-346a8629a0a1)
when icon is clicked:
![image](https://github.com/user-attachments/assets/41c18291-19f3-44a7-a56e-1cbc0f422b5c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Bhoomysingh10** [comment]
Hello @Anjaliavv51 , Could you kindly take a moment to review it and let me know if everything looks correct? If it's all good, please feel free to assign me :) .

**Comment by Anjaliavv51** [comment]
@Bhoomysingh10 go ahead.
