### ISSUE TITLE
✨[feature Request]: Changing Navbar

### ISSUE THREAD

**Issue by Anjaliavv51** [Anjaliavv51/Retro#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Need to improve navbar UI

### Benefits

First Come First serve who will ping first will be assigned first and awrded level 3 , they need make UI navbar Great and also , navbar should be implemented to all html pages in repo.

### Add ScreenShots

Before :

![image](https://github.com/user-attachments/assets/a79ff014-b47c-4855-8c41-86b3c0b59a93)

After :

Their should be a floating navbar , with curved edges and on hover over the link's , underlining should be displayed with glowing effect.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@everyone

**Comment by Mayukh-Mandal2005** [comment]
Hey @Anjaliavv51 
How do you want you navbar?
As the pic you uploaded is not visible
Kindly update me with the details as I am ready to work on this issue

**Comment by Mayukh-Mandal2005** [comment]
Please assign me this issue @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 
https://meet.google.com/xqp-vcii-ktj
please join the meet

**Comment by Mayukh-Mandal2005** [comment]
Hey @Anjaliavv51 
I was working on the navbar ui and then saw that the navbar could not be margined from the right side of the edge of page
![image](https://github.com/user-attachments/assets/f10997a9-28fd-4d7b-a8a9-24d8da4daf22)
I don't know what is the issue
So should I leave it like this?

**Comment by Anjaliavv51** [comment]
> Hey @Anjaliavv51 I was working on the navbar ui and then saw that the navbar could not be margined from the right side of the edge of page ![image](https://private-user-images.githubusercontent.com/135952646/373859427-f10997a9-28fd-4d7b-a8a9-24d8da4daf22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjA1MzcsIm5iZiI6MTcyODEyMDIzNywicGF0aCI6Ii8xMzU5NTI2NDYvMzczODU5NDI3LWYxMDk5N2E5LTI4ZmQtNGQ3Yi1hOGE5LTI0ZDhkYTRkYWYyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwOTIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzdlMjc3MzJjNGMwZWJiNzFhMzkxNjI4ZTYzNzdmZmMyZTg3MTZkNDU0NGY1YzNiMmZlMzYyYmEwMjk2YmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uEHyJEO0jgWGXHW_ihpKXKNlMwLPms5NU2LesK9PSNk) I don't know what is the issue So should I leave it like this?

It looks great, Please implement it to all html pages

**Comment by Mayukh-Mandal2005** [comment]
Okay sure Ma'am

**Comment by vishnuprasad2004** [comment]
issue #299 to imporve the nav bar further
