### ISSUE TITLE
🐞[bug]: Contact Page Appears to be wrong

### ISSUE THREAD

**Issue by subin-shk** [Anjaliavv51/Retro#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The contact page seems to jumbled. There is another "Feel free to Contact us" section inside the "Feel free to Contact us" section. The footer on the Contact page is not being aligned well.

### Expected behavior

The email, phone number and name show fit inside the border.  There should be only one "Feel free to Contact us"

### Add ScreenShots

![image](https://github.com/user-attachments/assets/84b0ac5e-3a81-48a3-83bf-821ef1558757)
![image](https://github.com/user-attachments/assets/0e0a7e81-4ea4-4038-a16f-2d1d14418d04)

![image](https://github.com/user-attachments/assets/b8f6c27f-ca6d-47a3-b39d-4330073f32e7)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@subin-shk already assigned. please create another issue.
