### ISSUE TITLE
🐞[bug]: Sider Navbar + responsiveness +contact Page UI

### ISSUE THREAD

**Issue by srishti023** [Anjaliavv51/Retro#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The website requires several fixes to improve its overall functionality and user experience. The issues include problems with the Sider Navbar, lack of responsiveness across different screen sizes, and UI improvements needed on the Contact Page.

### Expected behavior

1. There is not sidebar navigation for Mobile or other screen size which affect the User experience:
![Screenshot 2024-10-05 101012](https://github.com/user-attachments/assets/28ea7209-0813-4439-ad0a-9546e0df09a3)
Solution : I will improve this by making sidebar navigation.

2. Some of the pages are not responsive Like Login and Signup page.
![Screenshot 2024-10-05 101130](https://github.com/user-attachments/assets/9ced44cc-d7ac-4649-818e-8972ce1f9f67)
![Screenshot 2024-10-05 101213](https://github.com/user-attachments/assets/70a62124-5b6f-4873-a277-463c70e42cc6)
![Screenshot 2024-10-05 100935](https://github.com/user-attachments/assets/81df9607-9375-425c-b21c-13f70f465103)

Solution : I can use media queries to make it responsive which improves the User experience of whole site.

3. Contact UI is not Fixed
![Screenshot 2024-10-05 102142](https://github.com/user-attachments/assets/316b446e-f784-4bdb-84da-b0b7b710bc40)
Solution : I can Meet the UI of this contact page with all other pages. My implementing Attractive CSS.

Kindly assign me this so that i can work on this project .
Thankyou!
Best Regards!

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by srishti023** [comment]
Please assign me to fix this Issue!

**Comment by Anjaliavv51** [comment]
@srishti023 these are already assigned and they are on the way to be implemented.

**Comment by BhavikaPachauri** [comment]
I would like to solve this issue
