### ISSUE TITLE
UI Optimization for Boxes and Contact Us Page

### ISSUE THREAD

**Issue by Kavish-Paraswar** [Anjaliavv51/Retro#208]
The length of the "Click and Collect" and "Delivery" boxes should be reduced, especially if no images are going to be added, to improve the overall UI. Also the email input tag is less in length as before.
![image](https://github.com/user-attachments/assets/0c8d3957-387b-4c1b-a2f4-a5b497d82351)

The three boxes located below have the same issue. Their length should also be reduced for better design consistency.
![image](https://github.com/user-attachments/assets/07bc91ec-2725-469b-b494-29c473f0b5c2)

Given my strong background in HTML, CSS, and JavaScript, I would like to request that this task be assigned to me. I intend to mark this under the GSoC extended projects and level 2 atleast .

**Comment by Anjaliavv51** [comment]
Contact page is assigned, edit the issue name such that only for the UI optimization of Boxes is needed @Kavish-Paraswar , then I will assign u the issue.

**Comment by Kavish-Paraswar** [comment]
the comment has been updated

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar go ahead.
