### ISSUE TITLE
Changing the our services page completely

### ISSUE THREAD

**Issue by shivamv003** [Anjaliavv51/Retro#212]
![image](https://github.com/user-attachments/assets/df699f45-7a71-4250-a40c-b8b0f7bc2cc6)

this screen looks too bogus i want to update and give it a clean look like on one side it will having the description and on the other side it will having cards to make it look better

kindly assign me this under gssoc

**Comment by Anjaliavv51** [comment]
@shivamv003 send preview of your changes.

**Comment by shivamv003** [comment]
@Anjaliavv51 
![image](https://github.com/user-attachments/assets/2646f2d8-f1ee-4e9f-94de-64929a347562)

this type of service page I want to design

kindly assign this task to me under gssoc

**Comment by Anjaliavv51** [comment]
@shivamv003 make sure service box content is related to Retro theme , go ahead , I am assigning u.

**Comment by Akanshaku** [comment]
pls assign me this I would make it look more enhanced @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Akanshaku it is already assigned to @shivamv003
