### ISSUE TITLE
✨[feature Request]: Improving navbar for collections, about, services, contact us page

### ISSUE THREAD

**Issue by saiprasanna56** [Anjaliavv51/Retro#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am requesting the extension of the existing navbar UI to all pages within the project. Currently, the navbar is only implemented on the homepage, limiting its functionality across the site. The goal is to ensure that the navbar design, links, and functionality are consistent and accessible on every page, allowing users to easily navigate between different sections. 

### Use Case

For the project, this feature would enhance usability by providing a consistent and cohesive navigation experience across all pages. It ensures that users can easily access different sections of the project without confusion, improving overall user engagement and satisfaction. A uniform navbar UI also contributes to a more polished and professional look, making the project more intuitive to navigate.

### Benefits

Here are the key benefits of enhancing the navbar UI for the remaining pages:

Improved Navigation: Users can easily move between different pages, enhancing their overall experience and reducing frustration.
Consistency: A uniform navbar design across all pages gives the project a cohesive and professional look.
Better User Engagement: With a smoother navigation experience, users are more likely to explore the project further.
Increased Usability: A well-designed, consistent UI simplifies interactions and improves accessibility.
Enhanced User Trust: A polished UI makes the project appear more reliable and well thought out, increasing user confidence.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@saiprasanna56 it is already assigned
