### ISSUE TITLE
🐞[bug]: Misalignment in Navbar

### ISSUE THREAD

**Issue by Bhum-ika** [Anjaliavv51/Retro#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Logo of the website is not aligning well with other navbar links

### Expected behavior

It should be aligned

### Add ScreenShots

![image](https://github.com/user-attachments/assets/041ff06e-c25b-4d95-9778-508596a843f8)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Bhum-ika it going to be updated it is already assigned.
