### ISSUE TITLE
✨[feature Request]: Add Hover Effect and Change Cursor to Pointer on Marquee Text

### ISSUE THREAD

**Issue by shashankgoud18** [Anjaliavv51/Retro#217]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

I would like to request a new feature to enhance the user experience on the marquee text by adding a hover effect and changing the cursor to a pointer. This will make the text more interactive and visually engaging, especially when the text contains promotional or clickable information.

### Use Case

This feature will be useful for scenarios where the marquee contains important promotional information or calls to action, such as a "Get 30% OFF" offer. The hover effect and cursor change will make it more obvious to users that the text is meant to grab attention or prompt interaction.

### Benefits

1.Increased User Engagement: Hover effects and cursor changes grab attention, encouraging interaction with promotional content.
2.Better User Experience (UX): Clear visual cues help users understand the text is clickable, reducing confusion.
3.Improved Visual Appeal: Subtle animations make the design feel modern and dynamic.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@shashankgoud18 give preview of your feature either by screenshot or by screen recording

**Comment by shashankgoud18** [comment]
https://github.com/user-attachments/assets/35037c49-2ef5-4a65-b301-3c182c41de86

Changes Implemented:

1.Added a hover effect to the marquee text for better user interaction.
2.On clicking the marquee text, the user is redirected to the cart.html page, where a coupon code is generated.

**Comment by Anjaliavv51** [comment]
@shashankgoud18 go ahead
