### ISSUE TITLE
Changes in contact us page

### ISSUE THREAD

**Issue by AbhishekKusabi** [Anjaliavv51/Retro#218]
* There's an alignment issue with the contact us page
* The form in contact us page is not up to mark,
here are the screenshot's of the same issue

![image](https://github.com/user-attachments/assets/c1828e88-b2c7-4322-98c9-cd3388158b57)
![image](https://github.com/user-attachments/assets/329f9979-3822-4255-a77c-60be3707b10b)

I request you to assign me to do this task.

**Comment by AbhishekKusabi** [comment]
@Anjaliavv51 I would like to work on this issue.

**Comment by Anjaliavv51** [comment]
@AbhishekKusabi it is already assigned.
