### ISSUE TITLE
🐞[bug]: In services section when we hover on last two cards text is not visible

### ISSUE THREAD

**Issue by saiprasanna56** [Anjaliavv51/Retro#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug occurs when hovering over the last two cards in the services section. The text on these cards is white, and the hover background color is also white, causing the text to become invisible or hard to read due to the lack of contrast. This results in a poor user experience, as the text essentially disappears during the hover state.

### Expected behavior

The expected behavior is that when hovering over the last two cards in the services section, the text should remain clearly visible and easily readable. Ideally, the text color should either change to a contrasting color or the hover background color should be adjusted to ensure sufficient contrast between the text and the background. This would maintain readability and improve the user experience.

### Add ScreenShots

![Screenshot 2024-10-05 172248](https://github.com/user-attachments/assets/76d14730-0eff-4cac-a40c-16ff094bf2f9)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@saiprasanna56 go ahead.

**Comment by saiprasanna56** [comment]
> @saiprasanna56 go ahead.

Thank you for assigning me the issue @Anjaliavv51 . Kindly review and accept my pull request.
