### ISSUE TITLE
✨[feature Request]: Update the Navbar UI

### ISSUE THREAD

**Issue by Mayukh-Mandal2005** [Anjaliavv51/Retro#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Retro logo is not in sync with the other elements of the navbar on the pages about us, collection, services, cart etc.
Also, some elements of the navbar are not available on certain pages such as the about us is not there on about page and further more.
![image](https://github.com/user-attachments/assets/7bd4ae14-7b3d-4839-836e-8caf6faf4fc1)
![image](https://github.com/user-attachments/assets/2255024e-8f39-4d0c-b56d-c1b5e6028dff)

### Use Case

This feature of navbar will make all the elements of the in sync with each other alongwith the logo of the page.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Mayukh-Mandal2005** [comment]
Hey @Anjaliavv51 Mam
I know how to fix the retro logo on all the pages and i can also add the tab elements on all the pages
Please assign me this issue mam

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
Mam please provide level to this issue

**Comment by Anjaliavv51** [comment]
I will add to the PR
