### ISSUE TITLE
🐞[bug]: Improve Image Lazy Loading

### ISSUE THREAD

**Issue by shreyad2806** [Anjaliavv51/Retro#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Large images are slowing down page load time, especially on mobile devices. 

### Expected behavior

Implement image lazy loading to improve performance and load time.
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@shreyad2806 add screenshot of the Bug.

**Comment by Anjaliavv51** [comment]
@shreyad2806 go ahead!
