### ISSUE TITLE
📝[documentation Update]: upload a video of the website

### ISSUE THREAD

**Issue by Amulya-B28** [Anjaliavv51/Retro#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Making the appearance of readme file more appealing

### Suggested Change

adding a working video of the website as a user guide.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Amulya-B28** [comment]
Can you please add the level tag.

**Comment by Amulya-B28** [comment]
@Anjaliavv51 can you please assign this task to me

**Comment by Anjaliavv51** [comment]
@Amulya-B28  go ahead.
