### ISSUE TITLE
UI Improvements: Navbar, Images, and Social Icons

### ISSUE THREAD

**Issue by AswaniBolisetti** [Anjaliavv51/Retro#25]
Issue Description:
I've noticed the following UI issues:

1. Navbar blends with content while scrolling (no background).
2. Images are not attractive or relevant.
3. Social icons don’t fit the design.

**Comment by AswaniBolisetti** [comment]
I’d like to work on:

1. Adding a background to the navbar.
2. Replacing the images with better ones.
3. Updating the social icons with modern alternatives.
Please assign these issues to me.

**Comment by Anjaliavv51** [comment]
@AswaniBolisetti please give preview video of features.

**Comment by AswaniBolisetti** [comment]
@Anjaliavv51 
![1](https://github.com/user-attachments/assets/df3fb5a7-88c3-4ef1-9755-c76408fa8eac)
![2](https://github.com/user-attachments/assets/44c842fc-56ea-460e-b304-894217e79d53)
![3](https://github.com/user-attachments/assets/03afedd4-a935-4384-9493-639491b18762)
in the first image, the nav is not properly visible because of no background color, i can add that background color
in the second, i can add attractive images instead of them
in the third, i can add some effects to those social icons
please assign this task to me

**Comment by Anjaliavv51** [comment]
These are already on the way to be adjusted!
Create another issue.
