### ISSUE TITLE
enhancing README.md

### ISSUE THREAD

**Issue by Harshitha-Annam** [Anjaliavv51/Retro#255]
I’ve have gone through the README.md  and I really appreciate the work you’ve put into it! I noticed a few areas where some minor  wording adjustments could enhance clarity and readability.

If you’re open to it, I’d love to help with those changes or discuss some suggestions I have. So, Please assign me this issue.

**Comment by Yashwanth112004** [comment]
Please assign me this issue. I will enhance it.
