### ISSUE TITLE
FIXING THE CONTACT PAGE

### ISSUE THREAD

**Issue by RAJIV81205** [Anjaliavv51/Retro#256]
THE PAGE IS SPOILED ASSIGN ME TO FIX IT 
![image](https://github.com/user-attachments/assets/3a11c080-3877-4460-9306-cc2212fad942)

**Comment by Yashwanth112004** [comment]
Please assign the issue assign it to me

**Comment by Anjaliavv51** [comment]
@Yashwanth112004 already assigned @RAJIV81205

**Comment by RAJIV81205** [comment]
@Anjaliavv51 , I am not assigned

**Comment by Yashwanth112004** [comment]
Mam, he is not assigned it seems.
Please assign me

**Comment by RAJIV81205** [comment]
@Anjaliavv51 , I created this issue at first , So please assign me

**Comment by Anjaliavv51** [comment]
@Yashwanth112004 @RAJIV81205  it is already assigned to some other person, their PR is under review
