### ISSUE TITLE
🐞[bug]: The contact us page is messed up 

### ISSUE THREAD

**Issue by aditya07389** [Anjaliavv51/Retro#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

# hey @Anjaliavv51 ,
i was looking at your website and i must say i love the ui of the website and its concept too .
# i noticed that there is some issue with the contact us page (primarily css based issues )
i would love to look into it and resolve it .
i have attached the screenshot of the issue i noticed 
please assign this issue to me with the labels 'gssoc extd' and 'hactoberfest'.
looking forward to collaborate.

### Expected behavior

a uniform and more sought out contact us page without the existing document issues

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c5bfcc7d-fdfb-4282-9d77-3ed673130e92)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Kavish-Paraswar** [comment]
I would like to work on this
