### ISSUE TITLE
✨[feature Request]:  Want to improve design of cart page

### ISSUE THREAD

**Issue by Mr-DK07** [Anjaliavv51/Retro#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 I wanted to improve design of the cart page.  

### Use Case

This feature enhance the user experience.

### Benefits

enhance the user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Mr-DK07 please add preview video of feature.

**Comment by Mr-DK07** [comment]
@Anjaliavv51 if you assign me this, I can improve the UI/UX of the cart page.

**Comment by Mr-DK07** [comment]
> @Mr-DK07 please add preview video of feature.

@Anjaliavv51 First you assign me the task,  then I will be able to change in it.

**Comment by Anjaliavv51** [comment]
@Mr-DK07 go ahead!

**Comment by Mr-DK07** [comment]
@Anjaliavv51  please  add the tag Hacktoberfest Accepted and also the Level.

**Comment by Anjaliavv51** [comment]
@Mr-DK07 if issue has or not it won't check PR need to have it.

**Comment by Mr-DK07** [comment]
okay, don't forget to add level at the time of PR.

**Comment by Anjaliavv51** [comment]
@Mr-DK07 sure.
