### ISSUE TITLE
🐞[bug]: the retro text and the sign-up form are overlapping

### ISSUE THREAD

**Issue by iwanturequity** [Anjaliavv51/Retro#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The retro text ("Retro Vibe is Good Vibe") and the sign-up form are overlapping, causing both elements to appear on top of each other. This makes the form difficult to use and the text hard to read.

### Expected behavior

.The retro text should be clearly visible without obstructing or overlapping with the sign-up form.
.The sign-up form should be easily accessible and visually distinct, with no interference from background text or other elements.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d0f556cd-551b-4a48-be4d-8d0eb63eb71a)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@iwanturequity that is feature , their no overlapp , please create someother issue
