### ISSUE TITLE
Improving the About us page

### ISSUE THREAD

**Issue by komalnalage** [Anjaliavv51/Retro#269]
Hi @Anjaliavv51 .I think the about us page can be improved .
![image](https://github.com/user-attachments/assets/b3558fac-3f14-45b1-9b4e-e8625542b565)
Could you assign me this task and add labels gssoc-ext and hactoberfest-accepted?

**Comment by Varsha567** [comment]
hii @Anjaliavv51 could you please assign this to me

**Comment by Anjaliavv51** [comment]
@komalnalage go ahead.

**Comment by komalnalage** [comment]
Thank you @Anjaliavv51 i will send the PR once done

**Comment by Anjaliavv51** [comment]
@komalnalage okay
