### ISSUE TITLE
Fixing the UI of the services page

### ISSUE THREAD

**Issue by AnshikaaTomar** [Anjaliavv51/Retro#270]
I would like to improve the UI of the Services page.

As you can see in the screenshot below, there is a lot of gap which makes the webpage unattractive for the user. This can be fixed either by adding the image or reducing the gap

![ui of services page](https://github.com/user-attachments/assets/f6b8625f-d01a-46f8-887f-dd6d650ae64a)

Could you please assign this issue to me and add the necessary labels - gssoc-ext, hactoberfest-accepted and the level for it?

I am excited to contribute to this project: @Anjaliavv51.

**Comment by Anjaliavv51** [comment]
@AnshikaaTomar already assigned.
