### ISSUE TITLE
🐞[bug]: Order Now button not clearly visible

### ISSUE THREAD

**Issue by Khushi-Nigam** [Anjaliavv51/Retro#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/b9d820a0-b575-4bb6-a381-2ff7a9e7c748)
Order Now Button is not clearly visible in this section

### Expected behavior

The Order now button should be clearly visible 

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Khushi-Nigam it is already assigned.
