### ISSUE TITLE
🐞[bug]: Contact Us Form Not Responsive and Misaligned on Desktop Version

### ISSUE THREAD

**Issue by RaiDevX8** [Anjaliavv51/Retro#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
@Anjaliavv51 @Shanica-pandey @miss-world-09 
The "Contact Us" form is not responsive and is misaligned in the desktop version of the note-taking website. This affects the usability and appearance of the form.
![Screenshot 2024-10-06 175225](https://github.com/user-attachments/assets/2b6ec0f2-853b-437b-9850-6abdf05571ea)
![Screenshot 2024-10-06 175315](https://github.com/user-attachments/assets/78259d76-0686-4fa6-85dd-3d880c465905)

### Expected behavior

The "Contact Us" form should be responsive, adjusting to different screen sizes, and should be aligned properly in the desktop version.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by shubhrad1** [comment]
I would like to work on this issue.

**Comment by Anjaliavv51** [comment]
@RaiDevX8 it is already assigned.
