### ISSUE TITLE
✨[feature Request]: hover

### ISSUE THREAD

**Issue by abhi200446** [Anjaliavv51/Retro#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hovering the icons which looks better

### Use Case

 In a web application, hovering over icons can provide users with immediate feedbac

### Benefits

Improved User Experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/639cabfa-c13f-4d11-a3b8-4ae65976636d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by abishek1740P** [comment]
@Anjaliavv51 Assign me this issue. I'd love to work on this.

**Comment by Deepthi-Ramineni** [comment]
Can you please assign me this issue? I would like to work on it.

**Comment by Anjaliavv51** [comment]
@abhi200446 it is already done.
