### ISSUE TITLE
✨[feature Request]: add a payment option section and also improve the order now button 

### ISSUE THREAD

**Issue by HimangshuSharma01** [Anjaliavv51/Retro#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/a02f5d65-e61c-4fba-88d6-1d2109612287)
above the order now button we can add payment gateways  option also i can improve the order now button of the last page by adding animation

### Use Case

We need a payment gateway for orders

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@HS202022 already assigned

**Comment by HS202022** [comment]
who is assigned? if possible can i improve the order now button? i have a sample

https://github.com/user-attachments/assets/22af3793-a2e9-4960-a891-160d49d6849f
