### ISSUE TITLE
🐞[bug]: Services page need changes in the footer icons and Gaps in between 

### ISSUE THREAD

**Issue by laxmikandivalasa** [Anjaliavv51/Retro#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

footer icons are not enhanced on hover
irrelevant gaps between sections

https://github.com/user-attachments/assets/6a51d66b-2aea-47fb-b91b-99ca54e19608

### Expected behavior

some one else have just mentioned one feature enhancements but
I'd like to make all the corrections in the services page!
footer icons are not behaving on hover
There are irrelevant gaps in between elements
enhance the customer opinion  elements to more aesthetic

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@laxmikandivalasa go ahead.
