### ISSUE TITLE
🐞[bug]: improve contact us page 

### ISSUE THREAD

**Issue by Kratik1093** [Anjaliavv51/Retro#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the elements are not properly aligned

### Expected behavior

the elements should be placed properly

### Add ScreenShots

![Uploading Screenshot 2024-10-06 213553.png…]()

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Kratik1093 it is already assigned
