### ISSUE TITLE
🐞[bug]: Implement Toggle Feature for Showing and Hiding Answers

### ISSUE THREAD

**Issue by 2004vivek** [Anjaliavv51/Retro#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to implement a toggle functionality for a FAQ-style component. Each question should reveal its corresponding answer when clicked, and if clicked again, the answer should be hidden. This feature will enhance the user experience by allowing users to view answers only when needed

### Expected behavior

Each question should reveal its corresponding answer when clicked, and if clicked again, the answer should be hidden. This feature will enhance the user experience by allowing users to view answers only when needed

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c740ab25-fb12-4ed5-88f7-3be35c886ac8)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@2004vivek go ahead.
