### ISSUE TITLE
🐞[bug]: Footer icons in the Cart page is not changing on hover

### ISSUE THREAD

**Issue by laxmikandivalasa** [Anjaliavv51/Retro#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (242)](https://github.com/user-attachments/assets/f8ad4307-1e4c-45af-a4f7-6c5620a6671a)

### Expected behavior

smooth enhancement on hovering over footer icons (in cart page)which is similar to all other pages

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@laxmikandivalasa go ahead.
