### ISSUE TITLE
✨[feature Request]: improve the CoverPage and make it more attractive and aesthetic 

### ISSUE THREAD

**Issue by laxmikandivalasa** [Anjaliavv51/Retro#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot (245)](https://github.com/user-attachments/assets/9eff7cff-1d02-49e1-982f-31bfe064cd6c)
this page have no focus on elements like Retro,explore button
this would look great if it is clean 

### Use Case

Enhancing it with better background, good font for retro, good design for explore button

### Benefits

create a sense of attraction 
cool and aesthetic vide for users

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by laxmikandivalasa** [comment]
![Screenshot (253)](https://github.com/user-attachments/assets/84cb1769-7a71-43bb-8b83-9cf81c577f7b)


@Anjaliavv51 Enhanced it with better background  in coverpage 
I'd like to take any inputs
If you like it I'd like to contribute!

**Comment by Anjaliavv51** [comment]
@laxmikandivalasa go ahead.
