### ISSUE TITLE
Update 'Contact Us' page

### ISSUE THREAD

**Issue by sammy0318** [Anjaliavv51/Retro#295]
By looking at current 'Contact Us', i am very sure it needs some update as their are several issues .

![Screenshot (769)](https://github.com/user-attachments/assets/dcf667d1-a750-46c1-af6c-12149c17366b)
![Screenshot (770)](https://github.com/user-attachments/assets/867cc42d-13e2-4082-a52d-dc8da3be267f)
 @Anjaliavv51 , Please provide me chance to make some changes

**Comment by Anjaliavv51** [comment]
@sammy0318 it is already assigned.
