### ISSUE TITLE
🐞[bug]: input Fields are going out of bounds in the retro website

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [Anjaliavv51/Retro#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IN contact us section the input fields are going out of boundaries!!
so if given me a oppurtunity i will make that section more responsive!!
please assign me with the required labels as per gssoc'24 extended program

### Expected behavior

Contact us box will look clearer

### Add ScreenShots

![image](https://github.com/user-attachments/assets/09c3d6c4-7192-4c0d-b0a1-eb46c38f7e4b)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by rahulbamnuya** [comment]
I want to work on this issue

**Comment by Anjaliavv51** [comment]
@BVPKARTHIKEYA already assigned to others , please create other issue.

**Comment by BVPKARTHIKEYA** [comment]
okay thanks for informing!!
