### ISSUE TITLE
📝[documentation Update]: Featured in? Nothing is added there

### ISSUE THREAD

**Issue by neeru24** [Anjaliavv51/Retro#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Here, it's empty like featured in what??

![image](https://github.com/user-attachments/assets/b650754b-e7d9-46b7-941e-f2c2d5e57dfd)

### Suggested Change

GSSoC and Hacktober festt logos or images can be added to display that this project is a part of these.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@neeru24 go ahead.
