### ISSUE TITLE
✨[feature Request]: Hover Effects on Main page

### ISSUE THREAD

**Issue by neeru24** [Anjaliavv51/Retro#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When I opened the website, I noticed that it's well-designed, but I think adding a hover effect to the main welcome line could make it more dynamic. 

### Use Case

Right now, it feels a bit static, and adding this effect would enhance user engagement by drawing attention to the welcome message. I'd love to work on this if you could assign me the issue!

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a8e3e55a-374d-4a47-af8b-d61dffbd4461)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@neeru24 go ahead

**Comment by neeru24** [comment]
> @neeru24 go ahead

Thank you @Anjaliavv51 
I'll submit a PR by tonight and can you please add the level too.
