### ISSUE TITLE
OPTIMISATION FOR MOBILE SCREENS

### ISSUE THREAD

**Issue by HimangshuSharma01** [Anjaliavv51/Retro#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Optimization required for mobile screen and all other screen types

### Expected behavior

It should be optimised and responsive for mobile and all other devices I can fix it.

### Add ScreenShots

![Screenshot_20241007_095330](https://github.com/user-attachments/assets/3052c443-ee03-4249-b137-7e383270897d)
![Screenshot_20241007_095419](https://github.com/user-attachments/assets/6c1985d0-ba45-4894-a0fb-4e2e9888ddc7)
![Screenshot_20241007_095422](https://github.com/user-attachments/assets/f75f2cfd-4af3-4107-a81a-0aa376c68702)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@HS202022 go ahead.
