### ISSUE TITLE
misalignment of images in online order page

### ISSUE THREAD

**Issue by charitha-26** [Anjaliavv51/Retro#306]
I noticed that the images are not aligned properly in the respective boxes
I would like to fix the issue!
please assign it to me

![Screenshot 2024-10-07 113012](https://github.com/user-attachments/assets/66136317-f50b-45b9-bd64-0cd1c77097b4)

**Comment by Anjaliavv51** [comment]
@charitha-26 already assigned

**Comment by charitha-26** [comment]
> @charitha-26 already assigned

oh sorry!
