### ISSUE TITLE
✨[feature Request]: Dark mode 

### ISSUE THREAD

**Issue by harshgupta2125** [Anjaliavv51/Retro#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to added a dark mode button for a better user experience and some display modification  #303 for responsiveness 
would like to work on it . @Anjaliavv51  try to allow me . 

### Use Case

it effect on the design and view of the webpage and gives more creativeness for site and user view.

### Benefits

Better experience 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@harshgupta2125 go aheadm
