### ISSUE TITLE
🐞[bug]: Old Twitter logo in footer in place of X logo

### ISSUE THREAD

**Issue by Vd7905** [Anjaliavv51/Retro#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="884" alt="retro" src="https://github.com/user-attachments/assets/dcbb2162-5df7-4252-b080-e3bc4c522845">

Old Twitter logo in footer in place of X logo

### Expected behavior

X logo should appear in footer
@Anjaliavv51 could you please assign this issue to me i can fix this

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Vd7905 go ahead!
