### ISSUE TITLE
🐞[bug]: On the login page there is no option to switch to signup page

### ISSUE THREAD

**Issue by tarunkumar2005** [Anjaliavv51/Retro#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

So as you can see on the login page there is not option to switch to signup page for new user directly they need to come back and then go which is not good and not user friendly so we need to add a option for that.

### Expected behavior

So we can define don't have a account and link to signup page that will be better.
@Anjaliavv51 Assign this to under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e3bd5985-1dee-486f-8bd7-6f77355b27b2)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@tarunkumar2005 go ahead
