### ISSUE TITLE
✨[feature Request]:  ChatBot

### ISSUE THREAD

**Issue by trahulprabhu38** [Anjaliavv51/Retro#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i will add a chatbot to assist the user in understanding the retro concept even more .

### Use Case

user can clarify doubts with the bot. @Anjaliavv51  can you please assign me this task.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 go ahead

**Comment by anchalchaturvedi08** [comment]
Hi PA, I would like to work on this issue. Could you please assign it to me?
