### ISSUE TITLE
🐞[bug]: Incorrect Redirection from Home Button

### ISSUE THREAD

**Issue by amankumarcu** [Anjaliavv51/Retro#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking the Home button, I encounter the error message: "Cannot GET /Home.html". It seems that the button is not correctly configured to direct users to the index.html page.

Steps to Reproduce:

1. Navigate to the website.
2. Click on the Home button.

### Expected behavior

The Home button should redirect to the index.html page.

### Add ScreenShots

<video src="https://github.com/user-attachments/assets/e12239f8-c749-41fc-8602-e4b3926cebef">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by amankumarcu** [comment]
assign it to me so that i can raise a pull request.

**Comment by amankumarcu** [comment]
can you explain me the issue @Anjaliavv51 
<img width="1055" alt="Screenshot 2024-10-02 at 1 42 23 AM" src="https://github.com/user-attachments/assets/bb1554c7-7042-4811-9d16-b2c50ededc61">

**Comment by Anjaliavv51** [comment]
@amankumarcu don't bother about it.

**Comment by amankumarcu** [comment]
Ok then merge the pr. also i have sent your invite req on linkedIn from gmail : cse.amankumar@gmail.com

**Comment by Anjaliavv51** [comment]
@amankumarcu please mention issue number in the PR.

**Comment by Shalinis19137** [comment]
This shows error because : 
Home Page coding part is not added or written in this.

i fix it , Please it is Assign to me
