### ISSUE TITLE
🐞[bug]:  enhancing the alert on the cart page

### ISSUE THREAD

**Issue by tarunkumar2005** [Anjaliavv51/Retro#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the cart section there you see a alert which is not good and makeing the website look down.

### Expected behavior

SO what we can do is we can create a custom popup and use it to show that thing not a default js alert that will be better and enahnce the ui/ux of the website.
@Anjaliavv51 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/44b54b84-a3be-49cf-b9f9-cd603f21c759)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@tarunkumar2005 go ahead

**Comment by tarunkumar2005** [comment]
@Anjaliavv51 Can you check the PR its been a long time since it is active.
