### ISSUE TITLE
🐞[bug]: Without login accessing the cart page

### ISSUE THREAD

**Issue by tarunkumar2005** [Anjaliavv51/Retro#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Right now we can access the cart page without the user login or signup which is not a expercted behaviour.

### Expected behavior

So it should be first verified that user is logged in right we can do that by a protected route with a middleware.
@Anjaliavv51 Assign this to under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/368749d7-9395-486f-a5b4-68f34e862c80)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by vundrakondaIndira** [comment]
Hi @Anjaliavv51 

Could you please assign this issue to me I would like to work on this.

Thanks

**Comment by tarunkumar2005** [comment]
> Hi @Anjaliavv51
> 
> Could you please assign this issue to me I would like to work on this.
> 
> Thanks

@vundrakondaIndira Bro try to find your own issues and solve them don't steal others okay and it is first come first serve so don't try to steals others issues it will get you nowhere do your own work. i have seen you previously also commenting of my issue i think don't do that it is second time i am seeing you.

**Comment by tarunkumar2005** [comment]
I will report it next time if you didn't stopped and i have seen you another time doing same thing

**Comment by Anjaliavv51** [comment]
@tarunkumar2005 cool down and go ahead , to solve this issue.

**Comment by tarunkumar2005** [comment]
@Anjaliavv51 Can you check the PR its been a long time since it is active.
