### ISSUE TITLE
✨[feature Request]: Booknow page enhancement

### ISSUE THREAD

**Issue by Ananya-vastare** [Anjaliavv51/Retro#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to enhance the booknow page by adding a beautiful color palette which enhances the **users readability** and also I have changed the alignment of the items present in the gallery by making sure that all the images are of the  **same size**.These provide a better layout , alignment for the look of the webpage which give out a retro theme to the web page and I have also changed the colors of the hover effect .This is the change I have made  

### Use Case

I have improved the "Book Now" page by incorporating a beautiful color palette that enhances user readability. The thoughtful selection of colors not only makes the text more legible but also creates a more inviting atmosphere for users, encouraging them to explore the options available.

In addition, I have adjusted the alignment of the items in the gallery by ensuring that all images are of the same size. This change provides a cohesive layout and improved visual alignment, enhancing the overall aesthetics of the webpage. The consistent image sizing contributes to a cleaner, more organized look, which significantly enhances the user experience.

To further enrich the page's appeal, I have also updated the colors of the hover effect. These changes contribute to a retro theme, creating a nostalgic vibe that resonates with users and adds character to the webpage.

Overall, these enhancements not only improve the visual quality of the "Book Now" page but also facilitate better navigation and interaction, leading to a more enjoyable experience for users.

### Benefits

This enhances the readability of the webpage

### Add ScreenShots

![Change2](https://github.com/user-attachments/assets/a3835479-d0c2-472a-ba13-dea5e3d7d069)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Ananya-vastare already assigned

**Comment by Ananya-vastare** [comment]
May I please know whether it will be merged or not @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Ananya-vastare Mention the PR number

**Comment by Ananya-vastare** [comment]
I will send it to you before 4 pm @Ananya-vastare if that's fine

**Comment by Ananya-vastare** [comment]
c84b6db  is the pr number
