### ISSUE TITLE
🐞[bug]: Pictures in "Our Collection" Section Not Loading Correctly

### ISSUE THREAD

**Issue by iarmaanx** [Anjaliavv51/Retro#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The images in the Our Collection section are not loading correctly. This issue impacts the user experience as users are unable to view the pictures in this section.

### Expected behavior

All images in the Our Collection section should load properly and be displayed in the correct format and size.

### Add ScreenShots

![Screenshot 2024-10-07 223504](https://github.com/user-attachments/assets/431d2c6a-bc5f-4872-be8e-15c29dd8fba3)

Please add the following labels:

gssoc-ext
hacktoberfest-accepted
level-2

I have experience with handling image rendering and debugging such issues. Please assign this issue to me.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@iarmaanx already assigned.
