### ISSUE TITLE
🐞[bug]: Non - Uniformity in Images in Services for Event Page

### ISSUE THREAD

**Issue by yeolesanskruti** [Anjaliavv51/Retro#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Images for reference -

![Screenshot 2024-10-07 223646](https://github.com/user-attachments/assets/15c45f31-6233-4d88-a512-639665e1bbef)
![Screenshot 2024-10-07 223655](https://github.com/user-attachments/assets/6530b6b9-2c9c-44b3-ada4-de2c79623e12)

### Expected behavior

After alignment -

![Screenshot 2024-10-07 223728](https://github.com/user-attachments/assets/f1d7c523-e668-4dde-b5d5-461dd9eaad6a)
![Screenshot 2024-10-07 223737](https://github.com/user-attachments/assets/c31ba776-c06f-4d58-aaa3-801163a1e926)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@yeolesanskruti go ahead.
