### ISSUE TITLE
✨[feature Request]: Add Dark Mode Toggle Button

### ISSUE THREAD

**Issue by priyashuu** [Anjaliavv51/Retro#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to implement a toggle button to switch between light mode and dark mode across the application. The toggle button should be accessible, user-friendly, and persistent across sessions.

### Use Case

Customization: Users can personalize their experience, enhancing satisfaction and engagement with the project.
Accessibility: Improves the visual accessibility of the project, making it usable for a broader range of users, including those with visual impairments.
Aesthetics: Modernizes the UI and gives users a choice, improving the overall look and feel of the project.
Brand Perception: Projects that offer dark mode are often seen as more advanced and user-friendly, potentially improving the project’s reputation.

### Benefits

Offering both light and dark modes caters to a wider audience, including users who prefer the aesthetics of dark mode or find it easier to focus on darker screens.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by priyashuu** [comment]
can you please add level also

**Comment by Anjaliavv51** [comment]
It will be added to the PR.
