### ISSUE TITLE
🐞[bug]: UI/UX Problems on Contact Us Page

### ISSUE THREAD

**Issue by sanikamandale17** [Anjaliavv51/Retro#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Description: There are multiple layout and functionality issues present on the Contact Us page, impacting user experience and page design. These issues are affecting the visibility and usability of the page elements.

Actual Behavior:

Two contact forms are displayed, one of which appears incomplete.

"features-branch" text is visible as a placeholder in the header section.

The "Follow Us" section overlaps with other content, making it difficult to read.

The "Send Message" buttons have inconsistent sizes between the two forms.

### Expected behavior

Expected Behavior:

Only one contact form should be visible and properly aligned.

The "features-branch" placeholder should be replaced with the correct content or removed.

The "Follow Us" section should not overlap with other content and should be properly aligned.

All buttons should have consistent sizes and styles.

### Add ScreenShots

![Screenshot (174)](https://github.com/user-attachments/assets/4d013add-06d6-4123-ad34-851c8f7d966f)
![Screenshot (173)](https://github.com/user-attachments/assets/80a246bd-4d3f-45bd-8a83-4ffb603f7417)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Lokesh11868** [comment]
I would like to work on this issue, could you please assign me?

**Comment by Anjaliavv51** [comment]
@sanikamandale17 go ahead.
