### ISSUE TITLE
📝[documentation Update]: Documentation Update for Retro

### ISSUE THREAD

**Issue by tatheer-fathima** [Anjaliavv51/Retro#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Enhance the README.md file to include sections for a live demo, features, and contact information to provide users with comprehensive insights into the Retro platform and improve user engagement.

@Anjaliavv51 Ma'am Please assign me this under gssoc-ext'24 and hactoberfest
I would like to work on it.

### Suggested Change

1.Add a Live Demo Section
2.Add a Features Section
3.Add a Contact Information Section

### Rationale

 **Demo:** Including a live demo provides potential users and contributors with an immediate and engaging way to understand the platform's functionality and aesthetics. This can lead to increased user interest and potentially higher adoption rates.

**Features:** Clearly outlining the features of the Retro platform helps users quickly grasp the unique offerings, setting expectations and enhancing user satisfaction. It can also assist contributors in understanding the project scope and areas for potential improvement or feature requests.

**Contact Information:** Providing clear contact information fosters a sense of community and encourages users to reach out with questions, suggestions, or issues. This transparency can build trust and enhance user engagement, ultimately contributing to the project's success.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@T-Fathima go ahead.
