### ISSUE TITLE
✨[feature Request]: Improving the designing

### ISSUE THREAD

**Issue by AyutheCoder** [Anjaliavv51/Retro#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can improve the design or arrangement of this section.Please provide GSSOC Ext 2024 and hactoberfest label to it.![improve](https://github.com/user-attachments/assets/30d87d86-9a53-4946-a59e-622bc28c3bc0)

### Use Case

I helps me in improving my working with websites

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@AyutheCoder give me preview video of your idea.

**Comment by AyutheCoder** [comment]
Somewhat like this and more,it's just a preview.
https://github.com/user-attachments/assets/b70845bf-af41-41ad-8833-b01b7cf6cd09
![add ](https://github.com/user-attachments/assets/e86cf57f-0fc9-49da-880b-453ba7eb0c72)

**Comment by Vivisteria11** [comment]
I could improve the products page too, could you assign it to me .

**Comment by Anjaliavv51** [comment]
@AyutheCoder present one looks good no need these changes.
