### ISSUE TITLE
✨[feature Request]: add text animation using gsap

### ISSUE THREAD

**Issue by priyashuu** [Anjaliavv51/Retro#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Objective: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

### Use Case

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@priyashuu go ahead

**Comment by priyashuu** [comment]
Could you please review pull request #340 and merge it when you get a chance? Once it’s merged, I can start working on this issue.
