### ISSUE TITLE
✨[feature Request]: Adding hover effect for cards in service section

### ISSUE THREAD

**Issue by saiprasanna56** [Anjaliavv51/Retro#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To enhance user experience and interactivity on the service section of the website by implementing a visually appealing hover effect on service cards. This feature aims to draw users' attention to the services offered, encouraging them to engage more with the content.

### Use Case

The service section of the website provides users with essential information about the various services offered. Adding a hover effect to the service cards will improve user interaction and make the browsing experience more enjoyable.

### Benefits

Implementing hover effects on service cards brings multiple benefits to both the project and its community. By enhancing user experience and engagement, providing valuable insights, and establishing a modern aesthetic, this feature can significantly contribute to the project's success and growth within its target audience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@saiprasanna56 go ahead!

**Comment by saiprasanna56** [comment]
@Anjaliavv51 can you please merge my pull request
