### ISSUE TITLE
🐞[bug] Follow Us social media icons aren't looking right on about page

### ISSUE THREAD

**Issue by Riyachauhan11** [Anjaliavv51/Retro#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the icons arent looking consistent with their design right now. i want to work on fixing that.

### Expected behavior

the padding needs to be improved.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/463f8b2d-0566-4a3b-a839-b8aeb011472a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Riyachauhan11 go ahead!
