### ISSUE TITLE
✨[feature Request]:  Want to improve the design of Signup & Login page 

### ISSUE THREAD

**Issue by rishu6263** [Anjaliavv51/Retro#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current login and signup pages have a retro aesthetic but need improvements. This feature focuses on enhancing layout, typography, form design, and responsiveness for a modern, user-friendly experience.

### Use Case

By improving the form alignment, readability, and responsiveness, users will have a smoother experience, whether on desktop or mobile. This will make logging in and signing up more intuitive.

### Benefits

Improved User Experience: Cleaner interface and better usability.
Mobile Responsiveness: Optimizes design for various devices.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by rishu6263** [comment]
Please assign this to me.

**Comment by abishek1740P** [comment]
@Anjaliavv51 Assign me this issue. I'd like to work on this.

**Comment by Anjaliavv51** [comment]
@abishek1740P make sure to create the issue of ur own before others had , don't pls comment under others issue , it's my humble request.

**Comment by Anjaliavv51** [comment]
@rishu6263 go ahead.
