### ISSUE TITLE
🐞[bug]: Contact us form is not designed well

### ISSUE THREAD

**Issue by neeru24** [Anjaliavv51/Retro#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hii, In the CONTACT US page, FORM is not designed well. It has inconsistent styling. Form is duplicated in another form and no proper spacing for the text.

### Expected behavior

I'd like to work on this issue and design a  well structured form.

Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/98f15af4-ee21-400d-b78a-0377dfa3e021)
![image](https://github.com/user-attachments/assets/0dc9bee9-2b12-4163-a362-235043560ddb)
![image](https://github.com/user-attachments/assets/e09b6491-4203-4489-af52-6e80d2e2047a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@already assigned
