### ISSUE TITLE
🐞[bug]: Reduce Height of "Order Online" and "Track Your Order" Container

### ISSUE THREAD

**Issue by snehhhcodes** [Anjaliavv51/Retro#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the "Order Online" and "Track Your Order" sections on our website have containers that are excessively tall, leading to a disproportionate use of space on the page. This design choice contributes to a cluttered user interface, making it difficult for visitors to navigate effectively. 

### Expected behavior

The container heights should be reduced to a minimal, appropriate level, ensuring they do not take up more space than needed. This will result in a cleaner layout with no wasted space. The changes should be responsive across all devices to maintain usability and visual consistency.

### Add ScreenShots

![Screenshot 2024-10-09 021523](https://github.com/user-attachments/assets/147fd441-0124-44af-b66e-3a7d8059c94c)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by snehhhcodes** [comment]
@Anjaliavv51 Please review this issue once and if suitable assign it to me under appropriate GSSOC and Hacktoberfest level

**Comment by Anjaliavv51** [comment]
@snehhhcodes go ahead.
