### ISSUE TITLE
✨[feature Request]: Improve Font and Color for Better Visibility

### ISSUE THREAD

**Issue by Mehtarishita** [Anjaliavv51/Retro#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current font and color on the website lack visibility, affecting readability and user experience, especially for users with visual impairments. I propose adjusting the font color for better contrast, selecting a more readable font style, and ensuring consistent font sizes across the site. Additionally, these changes should be tested against WCAG accessibility standards to improve usability for all users.

Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

### Use Case

This feature would improve readability and ease of navigation, making the content more accessible across devices. Enhanced accessibility would also benefit a wider audience, improving the overall user experience.

### Benefits

Enhances readability and user experience, improving engagement and satisfaction.
Increases accessibility for users with visual impairments or different screen types.
Ensures compliance with accessibility standards like WCAG, promoting inclusivity.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/98abdb55-f617-4f7b-8d62-d1b502803428)
The grey colored description is not visible.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Mehtarishita as per now it is not needed,create another issue.
