### ISSUE TITLE
✨[feature Request]: Add new column in cart for individual item total

### ISSUE THREAD

**Issue by saiprasanna56** [Anjaliavv51/Retro#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a new column in the cart to display the total cost for each item. This will be calculated as the price per item multiplied by the quantity, allowing users to easily see the itemized totals.

### Use Case

By adding an individual item total column to the cart, users will be able to easily see the total cost for each item based on the quantity they have selected. This will reduce confusion, as users won’t need to manually calculate totals, improving the overall shopping experience.

### Benefits

This feature aligns with a user-centered approach, providing a more efficient and error-free shopping experience, which can foster a stronger community of engaged users.

### Add ScreenShots

![Screenshot 2024-10-09 080341](https://github.com/user-attachments/assets/50f375c2-d2f3-473e-a197-82f9db855dbe)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@saiprasanna56 go ahead.
