### ISSUE TITLE
✨[feature Request]: Add a forgot password page

### ISSUE THREAD

**Issue by amitroy-thedev** [Anjaliavv51/Retro#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently there is only signup and login page but no forgot passsword page i want to work on that 

### Use Case

It will help users to reset password

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@amitroy-thedev make sure page matches UI of the repo

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 Sure.. level?

**Comment by Anjaliavv51** [comment]
@amitroy-thedev i will to the PR

**Comment by amitroy-thedev** [comment]
Hey @Anjaliavv51 i have implemented this way do i need to also add the left card also?
![image](https://github.com/user-attachments/assets/97b0061f-cdd2-4cd9-a666-8367a5eeda57)

**Comment by amitroy-thedev** [comment]
Hey @Anjaliavv51 I've implemented the forgot password page but i didn't added the left card is it fine ?
![image](https://github.com/user-attachments/assets/a7af87fd-2b31-4bb0-ae0b-490ae7ce6ee6)

**Comment by Anjaliavv51** [comment]
> Hey @Anjaliavv51 I've implemented the forgot password page but i didn't added the left card is it fine ? ![image](https://private-user-images.githubusercontent.com/104709542/374909238-a7af87fd-2b31-4bb0-ae0b-490ae7ce6ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTA1NjAsIm5iZiI6MTcyODQ5MDI2MCwicGF0aCI6Ii8xMDQ3MDk1NDIvMzc0OTA5MjM4LWE3YWY4N2ZkLTJiMzEtNGJiMC1hZTBiLTQ5MGFlN2NlNmVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNjExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTE5Mzg2MDk4YmI0ODljYjdmNjQxZDY0ODAwNzM5ODdkMzA2ZmM2NzY4ZTJjMWE0NTNmNzQ3NmFkMmM5MjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JiRrz3FGNIxw1SKkVsNFwSDnqkugOCy_VPEOSlLUHEU)

Yes , no issue , ur implementation is great!
