### ISSUE TITLE
Correcting the alignment of nav bar .

### ISSUE THREAD

**Issue by Tanushree084** [Anjaliavv51/Retro#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anjaliavv51 ,

I want to  correct the alignment of the nav bar making it look proper .
<img width="952" alt="image" src="https://github.com/user-attachments/assets/e7bb5007-6b22-4960-9ff5-f8c800169779">
 
Can you please assign me this issue?

### Use Case

Alignment issues will be solved.
Making it more proper after opening the website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by sayiamarora** [comment]
Hi @Anjaliavv51 I have seen that navbar is not proper the way it should be, I would really appreciate if you could assign this task to me.

**Comment by Anjaliavv51** [comment]
@sayiamarora that design of the navbar itself , so not required
