### ISSUE TITLE
🐞[bug]: collection page footer 

### ISSUE THREAD

**Issue by Ishika-Singhal** [Anjaliavv51/Retro#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer of collection page is not responsive on different screens .The text of the footer is overlapping on each other.

### Expected behavior

Text of the footer section should be aligned and not overlapping.

### Add ScreenShots

![Screenshot (65)](https://github.com/user-attachments/assets/25d1a9db-f0d6-4de4-b8c9-617733804241)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Ishika-Singhal go ahead!
