### ISSUE TITLE
✨[feature Request]: Enhance  Navbar with Background Color and Hover Effects

### ISSUE THREAD

**Issue by Ayan-Khan79** [Anjaliavv51/Retro#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

* The current  navbar lacks a background color, which causes the navbar items to become difficult to read while scrolling over the content.

* Request to add a solid/semi-transparent background color to the sticky navbar for better visibility.
* Suggest adding hover effects to the navbar items to improve user experience and visual feedback during interaction.

### Use Case

Current Behavior:
The  navbar currently lacks a background color, making the text blend with page content while scrolling. As a result, it's difficult to see and interact with the navbar items, especially when the page background and navbar items have similar colors.

Desired Behavior:
The  navbar should have a solid or semi-transparent background color, ensuring that the navigation items remain easily visible regardless of the content behind it.
When hovering over navbar items, a subtle hover effect should give visual feedback, improving the user experience and interactivity.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/32449e78-de5d-4401-b217-2b005091f322)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Ayan-Khan79 update ur branch that is not the current navbar

**Comment by Ayan-Khan79** [comment]
@Anjaliavv51 I have pulled the updated branch now but it still shows the same flaw.....
![image](https://github.com/user-attachments/assets/dea9db71-5ec6-4af6-a478-30362a9c21e6)

**Comment by Ayan-Khan79** [comment]
Now its showing in the deployed Link
