### ISSUE TITLE
✨[feature Request]: improve the ui 

### ISSUE THREAD

**Issue by RiyaJain8114** [Anjaliavv51/Retro#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

improve ui of contact page 

### Use Case

for better user experience 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/930931ae-af95-42b0-8e9c-b5c8d6a0a7ea)

 improve the ui of this 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@RiyaJain8114 it is already assigned.
