### ISSUE TITLE
✨[feature Request]: Add functionality to display the 'Added to Cart' message below the product image.

### ISSUE THREAD

**Issue by krittika019** [Anjaliavv51/Retro#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In About page: 
1)  instead of triggering a pop-up alert, display the 'Added to Cart' message below the product image .
2) Add a cart-quantity badge to display the cart quantity.
3) Telephone image not visible.

### Use Case

1) Inline Cart Message: When users click the "Add to Cart" button on a product, instead of showing a pop-up alert, the message "Added to Cart" will appear directly below the product image. 

2) Cart Quantity Badge:
The cart icon will have a badge showing the current quantity of items in the cart. As users add products, the number will increase dynamically. This allows users to see how many items they've added at a glance without navigating away from the current page.

### Benefits

Improved Visual Feedback: Clear indication of added items.
Reduced Interruptions: Eliminates distractions from pop-ups.

### Add ScreenShots

1) ![pop](https://github.com/user-attachments/assets/9563e6f6-d801-46fb-9692-0f23e656db7c)

2) ![cart](https://github.com/user-attachments/assets/8d8ebd16-955f-4bcb-b5b6-789a3414123c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
Go ahead @krittika019
