### ISSUE TITLE
✨[feature Request]: add google icon in login with google

### ISSUE THREAD

**Issue by ChauhanAyush04** [Anjaliavv51/Retro#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there should be google icon in login with google section.
![Screenshot 2024-10-09 220857](https://github.com/user-attachments/assets/8f98e959-1871-4d57-8350-273c23878757)

### Use Case

it will show visually that you can also login with google.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@ChauhanAyush04 go ahead.
