### ISSUE TITLE
✨[feature Request]: removal of cursor

### ISSUE THREAD

**Issue by ChauhanAyush04** [Anjaliavv51/Retro#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot 2024-10-09 220857](https://github.com/user-attachments/assets/6c7c9d53-5a34-4e48-80e9-59172d6c24e2)
that drop cursor is very irritating.

### Use Case

it will not confuse user whether that drop is the cursor or the actuall arrow is the cursor

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@ChauhanAyush04 i wil do that. 

No need to raise an issue for that IMOA.
