### ISSUE TITLE
✨[feature Request]: add responsiveness to a section of home page

### ISSUE THREAD

**Issue by Riyachauhan11** [Anjaliavv51/Retro#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

currently the section of "Get ready to explore our vintage collections!" on home page is not responsive. I would like to fix this issue.
![image](https://github.com/user-attachments/assets/a9adcda8-9546-4fe0-9ad2-88c16f85e124)
![image](https://github.com/user-attachments/assets/4e1c420c-c2c3-4ade-b193-060fafba7d83)

### Use Case

improves user interaction

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by tulikaa25** [comment]
Please assign this issue to me as I am quite experienced in making websites responsive @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Riyachauhan11 go ahead.
