### ISSUE TITLE
🐞[bug]:  hover color change due to  user visibility ,

### ISSUE THREAD

**Issue by anish013326** [Anjaliavv51/Retro#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when we hover  arrow up icons . the icons not look for user 
![Screenshot 2024-10-02 034650](https://github.com/user-attachments/assets/00d2dd8d-c4af-4ce9-aa7b-d4b987d42e80)

on hover the element is hide 
![Screenshot 2024-10-02 034835](https://github.com/user-attachments/assets/a0e66e71-8f83-4289-b900-203438598b8f)

### Expected behavior

i want when user hover these arrow element we feels like we get some response from it

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
It is not needed currently.

**Comment by anish013326** [comment]
Hi [@Anjaliavv51 ],

Thank you for your feedback. I understand that the hover color change is not needed at the moment.

If there's any future work or updates required, please feel free to assign them to me. I'd be happy to assist!

Best regards,
Anish

**Comment by Anjaliavv51** [comment]
@anish013326 can u work on issue #9 i will assign u immediately
