### ISSUE TITLE
🐞[bug]: Improving the rating pattern on collection Page

### ISSUE THREAD

**Issue by Naveenkumar30838** [Anjaliavv51/Retro#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we hover on some specific star it just change the color of that specific star only and after clicking on it , it changes the color of the preceding stars .
ScreenShot 1 shows the behaviour of stars on hover

### Expected behavior

But it would be better if it behaves like : On hover the stars preceding the current start should also get colored , so that user can came to know of how many star rating they are going to give via UI / star color change . 
Screenshot 2 shows the behavious of stars on click and it should be the behaviour also on Hover

### Add ScreenShots

Screen Shot 1 : ![image](https://github.com/user-attachments/assets/40ed9a31-8e89-41f1-9800-f76ee4656e49)
Screen Shot 2 : ![image](https://github.com/user-attachments/assets/85106a46-9ed1-46c6-86fb-74dc488cb01b)

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Naveenkumar30838** [comment]
Assign this to me i can modify it according to the requirements

**Comment by tulikaa25** [comment]
Please assign this issue to me as I can resolve it correctly @Anjaliavv51
