### ISSUE TITLE
🐞[bug]: Aligning the Nav Items and changing the Hover Behavious of Logo

### ISSUE THREAD

**Issue by Naveenkumar30838** [Anjaliavv51/Retro#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. The Nav items seems not to be aligned properly in vertical direction
2. On Hovering the Retro logo's font changes abruptly / immediately and the font seem to go out of the context

### Expected behavior

The Nav Items should be aligned properly in vertical direction 
2. A transition could be added in the logo which will be effecting on hovering over the logo and the font size on hover should be adjusted accordingly .

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8efc11ca-f65a-4db0-a63f-f9460728f867)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Naveenkumar30838** [comment]
Assign this to me

**Comment by Anjaliavv51** [comment]
already assigned.
