### ISSUE TITLE
🐞[bug]: Change color of FAQ section according to website theme

### ISSUE THREAD

**Issue by nishtha-902** [Anjaliavv51/Retro#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Change color of FAQ section according to website theme
please assign me this

### Expected behavior

FAQ section must have proper color according to website theme

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5c71a2ae-ad29-4349-a348-7490104a8a0b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@nishtha-902 update ur branch & implement the changes.
