### ISSUE TITLE
🐞[bug]: Enhance UI of about page

### ISSUE THREAD

**Issue by nishtha-902** [Anjaliavv51/Retro#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

UI of about page must be enhanced and font-size must be small, please assign me this issue

### Expected behavior

Font-size in about page must be maintained

### Add ScreenShots

![image](https://github.com/user-attachments/assets/82560304-aea2-42d1-9334-3f4bb32c60b2)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Pragya79645** [comment]
I would like to work on this. Please assign it to me.

**Comment by Anjaliavv51** [comment]
@nishtha-902  go ahead.
