### ISSUE TITLE
🐞[bug]: Misaligned Elements on About Us Page-(Fixing about Us Page)

### ISSUE THREAD

**Issue by priyachau12** [Anjaliavv51/Retro#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

he About Us page layout appears disorganized, with misaligned elements that detract from readability and user experience. The page lacks consistent spacing and alignment, leading to a cluttered appearance.

### Expected behavior

The About Us page should have:

Proper alignment for each section and element
Consistent spacing and padding for a clean look
Improved readability by organizing elements in a logical, visually appealing flow

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6c3602b8-e81b-46f0-95bc-a1d16e0eff5c)
![image](https://github.com/user-attachments/assets/c33cabb4-cc60-4cce-b224-7eeb47b68571)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by hemant2807** [comment]
I have a animated contact us page and also a basic page which can match your UI. Kindly assign me the issue under gssoc extd. label so that I can contribute to it

**Comment by Anjaliavv51** [comment]
already assigned.

@hemant2807 create ur own issue properly.
