### ISSUE TITLE
✨[feature Request]: add images in the Cards

### ISSUE THREAD

**Issue by HeartTick** [Anjaliavv51/Retro#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i can add the images in the cards section and the  sizes of the cards are not similar i can work on the allot this task to me.

### Use Case

adding some good effects and images to the cards

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1f22c5c9-b040-4c81-8b8d-3d4667423ee6)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by abishek1740P** [comment]
@Anjaliavv51 assign me this issue . I'd like to work on this.

**Comment by ruchikakengal** [comment]
i like to add images in the images section which gives nice look to the webpage. assign me i like to work on it

**Comment by Anjaliavv51** [comment]
Issue is already been assigned.
