### ISSUE TITLE
Add footer section to your LOGIN menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [Anjaliavv51/Retro#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

assign me to make the footer section to your LOGIN MENU  which will enhance your UI/UX. also increase your user engagement 
A good footer section also helps with the branding of your company/product.

### Use Case

i will make an attractive footer section and attach it with your login menu 
so assign me for my contribution.

### Benefits

A good footer section will help you to enhance your UI/UX, and it will also increase the reach and engagement of users/clients.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Pranjalsinha110 not required
