### ISSUE TITLE
Add footer section in your SIGN IN menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [Anjaliavv51/Retro#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

assign me to make the footer section to your SIGN IN MENU, which will enhance your UI/UX. also increase your user engagement
A good footer section also helps with the branding of your company/product.

### Use Case

a good footer section enhances your UI/Ux and also increases your user engagement of your website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by gurramkarthiknetha** [comment]
i would like to work on this project .please assign it to me.

**Comment by Anjaliavv51** [comment]
@Pranjalsinha110 nnot required.
