### ISSUE TITLE
✨[feature Request]: Navigation Bar / Main Menu Arrangement

### ISSUE THREAD

**Issue by alokartist** [Anjaliavv51/Retro#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue: Navigation Bar / Main Menu Arrangement

**Description:**
The navigation bar (or main menu) is not properly arranged. The logo "RETRO" should be positioned so that it has a hover effect.

**Steps to Reproduce:**
1. Open the website.
2. Observe the arrangement of the navigation bar/main menu and the logo.

**Expected Behavior:**
The "RETRO" logo should be arranged to have a visible hover effect when the mouse is over it.

**Actual Behavior:**
Currently, the logo does not have the intended hover effect.

**Screenshots:**
![image](https://github.com/user-attachments/assets/d2770e6d-e706-4d2a-b9fb-524c37fede17)

**Suggested Fix:**
Please adjust the positioning of the "RETRO" logo to enable the hover effect.

### Use Case

To ensure the "RETRO" logo in the navigation bar is properly arranged and provides a hover effect to enhance user interaction.

### Add ScreenShots

![Screenshot 2024-10-10 143856](https://github.com/user-attachments/assets/f399ae11-35fb-4f5a-83bb-92b615f67ec6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@alokartist aleready assigned.
