### ISSUE TITLE
✨[feature Request]: 

### ISSUE THREAD

**Issue by Ash182004** [Anjaliavv51/Retro#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to make this contact us section more wider and attractive
![Screenshot 2024-10-10 163942](https://github.com/user-attachments/assets/8f678f9a-a3c0-4a6e-9b6a-7000b759f765)

### Use Case

it will make it lokk more attractive and eye catching

### Benefits

it will make it lokk more attractive and eye catching

### Add ScreenShots

![Screenshot 2024-10-10 163942](https://github.com/user-attachments/assets/2552b2aa-dbda-4836-89bf-096463d8aed8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Ash182004 go ahead.
