### ISSUE TITLE
✨[feature Request]: Add icons on the login card

### ISSUE THREAD

**Issue by Vaishh18** [Anjaliavv51/Retro#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot (1096)](https://github.com/user-attachments/assets/5af71ce2-ff7f-40ab-ba9e-0d9ef5b66b95)

![image](https://github.com/user-attachments/assets/c18befd2-54fe-4fb9-b519-af5f52ca685d)

The current login and signup pages card looks very plain and the ui seen unattractive.

### Use Case

I will add icons revelent to the site and make the ui of the site better.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by biswajit-sarkar-007** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by Vaishh18** [comment]
@Anjaliavv51 ,i would like to work on it ,also you liked my past changes ,also please merge the changes of pr #https://github.com/Anjaliavv51/Retro/pull/262

**Comment by Anjaliavv51** [comment]
@Vaishh18  go ahead.
