### ISSUE TITLE
IMPROVEMENT IN THE FOOTER SECTION OF THE ABOUT US PAGE

### ISSUE THREAD

**Issue by eshitatalukdar08** [Anjaliavv51/Retro#421]
Hello @Anjaliavv51, in the About Us page, some changes can improve the user experience. These changes include:
(i) Adjusting the height of the footer
(ii) Adding proper spacing and padding between elements
(iii) Adding small icons for home, about, services, etc.
(iv) Improving the placement of contents and colors
Please assign me to this task as I would love to contribute.
![Screenshot 2024-10-10 063509](https://github.com/user-attachments/assets/c56148f8-1d4c-471c-8428-0e38b9c69adf)

**Comment by MD-IRFAN-RAJ** [comment]
@Anjaliavv51, I would like to work on this issue. Please assign this to me .

**Comment by eshitatalukdar08** [comment]
Hey @MD-IRFAN-RAJ I have already raised the issue and commented first. Please raise some other issue

**Comment by Anjaliavv51** [comment]
@MD-IRFAN-RAJ it is already assigned.
