### ISSUE TITLE
want to work on contact us page

### ISSUE THREAD

**Issue by Kajalmehta29** [Anjaliavv51/Retro#424]
Content of the contact us page is scattered and overlapping. I want to fix this issue. Example is shown in the image but there is a lot to do.
Please assign this issue to me under gssoc-extd and hacktoberfest.

<img width="787" alt="Screenshot 2024-10-10 at 8 26 26 PM" src="https://github.com/user-attachments/assets/15e40f62-50ad-475a-8be7-a3c8025cd0b8">

**Comment by Anjaliavv51** [comment]
@Kajalmehta29 it is already assigned.
