### ISSUE TITLE
🐞[bug]: Improve text boxes gap & Header position

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Anjaliavv51/Retro#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the cursor is moved to the "Retro Vibe is Good Vibe" text box, the text box merges with the "SIGN UP" text box. which doesn't look very good।

https://github.com/user-attachments/assets/ee6745fb-15d5-4d2e-a4b9-0d501a3929d9

& the position of the Header is fixed across the page, causing it to blend in with other text, It preventing the website from looking better.

![Screenshot 2024-10-11 013920](https://github.com/user-attachments/assets/73b8094b-ae94-458a-93b4-4432ed1929b6)
![Screenshot 2024-10-11 013939](https://github.com/user-attachments/assets/4af58cca-ccaf-477f-aeb2-5d27a3205652)

I want to Fixed these two issue properly. @Anjaliavv51  please assign me this task.

### Expected behavior

I will fixed the text box gap & header position properly.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 PA kindly assign me this task & add level

**Comment by Anjaliavv51** [comment]
@Subhajit-2023-44  go ahead.
