### ISSUE TITLE
🐞[bug]: Missalignment of collection's page content 

### ISSUE THREAD

**Issue by srishti023** [Anjaliavv51/Retro#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer part of collection page is not aligned appropriatelly.

1. The texts should align with in the footer section.

![Screenshot 2024-10-11 131151](https://github.com/user-attachments/assets/9dfe0dbc-9213-4701-9a27-52e7db744211)

3. also the images is not centered

![Screenshot 2024-10-11 131131](https://github.com/user-attachments/assets/36b63ccd-29a3-485e-b9e7-932d02eaf5be)

5. contact form in the footer need to be adjusted better

![Screenshot 2024-10-11 130847](https://github.com/user-attachments/assets/1dbf053e-9088-497a-8e13-753d455a4fcd)

### Expected behavior

Page alignment played a big role for better UI It is important to make the layout in a good foemat.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@srishti023  go ahead.
