### ISSUE TITLE
🐞[bug]: Services page is not responsive 

### ISSUE THREAD

**Issue by srishti023** [Anjaliavv51/Retro#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The services page lacks the responsiveness in mobile screen.

https://github.com/user-attachments/assets/ef214d03-597f-4ef1-9e4e-bae6e774e932

### Expected behavior

I want to implement media queries for mobile screen to adjust the page content's alignment.
Please assign me this task ireally wanted to work on this porojec and fix this issue.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@srishti023  go ahead.
