### ISSUE TITLE
✨[feature Request]: Hover on question of FAQ will display answer

### ISSUE THREAD

**Issue by jvkousthub** [Anjaliavv51/Retro#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On hover of question of FAQ the answer will be be shown with smooth transition 
similar to faq here https://style-share.vercel.app/app/

### Use Case

It makes more good looking

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by jvkousthub** [comment]
@Anjaliavv51 I would like to work on this issue

**Comment by Anjaliavv51** [comment]
@jvkousthub  go ahead.
