### ISSUE TITLE
✨[feature Request]: FOOTER NOT LOOKING ATTRACTIVE

### ISSUE THREAD

**Issue by Ishika-codeit** [Anjaliavv51/Retro#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

FOOTER SHOLD BE OF DARK COLOR AND SOME ENHANCE VIBRATING FONT SHOULD BE USED IN IT

### Use Case

FOOTER IS THE BASIC DESCRIPTION OF ALL WEB SO IT MUST BE ATTRACTIVE

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Ishika-codeit** [comment]
@Anjaliavv51 KINDLY ASSIGN IT

**Comment by Anjaliavv51** [comment]
@Ishika-codeit  go ahead.
