### ISSUE TITLE
✨[feature Request]: Add forgot password in login page

### ISSUE THREAD

**Issue by SalehaTabassum** [Anjaliavv51/Retro#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add forgot password option to login page

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@SalehaTabassum it is alread assigned.
