### ISSUE TITLE
🐞[bug]: Contact Us Form Layout Misalignment on /html-files/contact

### ISSUE THREAD

**Issue by sagarbendale2004** [Anjaliavv51/Retro#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The contact form on the /html-files/contact route is not properly aligned, resulting in an unbalanced and visually unappealing layout. There appear to be issues with the CSS layout that need to be addressed for better form alignment and structure.

## Steps to Reproduce:

- Visit the [Contact Us page](https://rococo-mooncake-0d89f7.netlify.app/html-files/contact).
- Observe the layout of the form elements (input fields, labels, buttons, etc.).

## Actual Behavior:

- The form elements are misaligned, creating a disorganized layout.
- Some elements may not align with others, resulting in an inconsistent appearance.

### Expected behavior

The form should be neatly aligned with proper spacing between the elements (labels, input fields, buttons).
The overall layout should be consistent and visually balanced for a clean user interface.

### Add ScreenShots

![screencapture-rococo-mooncake-0d89f7-netlify-app-html-files-contact-2024-10-12-10_48_16](https://github.com/user-attachments/assets/80f7b1d9-abb2-405d-abb8-a74b390f9493)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by sagarbendale2004** [comment]
@Anjaliavv51 "Hi, I've noticed the layout issue with the contact form. I'd like to work on fixing the CSS alignment to make the form more organized. Could you please assign this to me?"

**Comment by Anjaliavv51** [comment]
@sagarbendale2004 already assigned.
