### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [Anjaliavv51/Retro#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

### Use Case

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@TBorundia go ahead.
