### ISSUE TITLE
🐞[bug]: Move to top hover is not visible on hover.

### ISSUE THREAD

**Issue by gyanshankar1708** [Anjaliavv51/Retro#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Move to up button is not visible upon hover. and also at the bottom due to white color is not visible 

### Expected behavior

Color combination should be change of Move to top button.

### Add ScreenShots

https://github.com/user-attachments/assets/59ab39b1-cc70-4441-adc7-01aa937c3b6c
![image](https://github.com/user-attachments/assets/e6eed99b-dccb-4bbd-a25f-f1260506e82e)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Not-Happening** [comment]
hi, pls assign this to me, I will do this!
