### ISSUE TITLE
✨[feature Request]: I would like to work on the nav-bar 

### ISSUE THREAD

**Issue by Vatsal-Verma** [Anjaliavv51/Retro#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![problem](https://github.com/user-attachments/assets/af666a92-6c2c-4357-98b9-4cc06607bfd7)

1) When we slide down the page then the nav bar hides , Due to this the nav links are not properly visible this can fixed by adding a backdrop filter to make it more visible.

2) I would also like to add a side nav bar while the website is in mobile view .

### Use Case

Better visibility of the nav links at the top , Better UI. Makes it easier for the person to find the desired path.

### Benefits

Right now nav link are not properly visible which makes it difficult to use the nav link to move to a different page. 
While the website is in mobile view it doesn't show any nav-links , so for that i would like to add a side nav bar at the top left position.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Vatsal-Verma it is already assigned.
