### ISSUE TITLE
🐞[bug]: Adding small icons in the input fields of  contact us page

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [Anjaliavv51/Retro#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i would love to add some small icons of name and email which makes the website even more better!
please assign me with the required labels as per gssoc'24 extended program

### Expected behavior

Website will look even more better!!

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@BVPKARTHIKEYA  go ahead.
