### ISSUE TITLE
🐞[bug]: Few issues I feel that could be elaborated for user

### ISSUE THREAD

**Issue by Arushi2S** [Anjaliavv51/Retro#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ON HOVERING THE "RETRO" AND "WELCOME TO RETRO" enlarges which I feel quite absurd as a website use. Especially the shaddow/neon effect on "WELCOME TO RETRO" don't match with aesthetics of website.I also suggest to change logo in navbar for maybe the same which you have in your website title. 

### Expected behavior

The hover effect must be modified .also implementation of better logo

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Arushi2S** [comment]
![Screenshot (114)](https://github.com/user-attachments/assets/62977061-46e4-4d4e-840a-e24b44bd57e2)
pr submitted now heading will look like this.

**Comment by Anjaliavv51** [comment]
> ![Screenshot (114)](https://private-user-images.githubusercontent.com/113857131/376050497-62977061-46e4-4d4e-840a-e24b44bd57e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzYyNTYsIm5iZiI6MTcyODgzNTk1NiwicGF0aCI6Ii8xMTM4NTcxMzEvMzc2MDUwNDk3LTYyOTc3MDYxLTQ2ZTQtNGQ0ZS04NDBhLWUyNGI0NGJkNTdlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNjEyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2IwNDc1MzYzNWQ5YmQ3NzQ5NGE2NjgyNTFiOWE5NzUwMTRmNDFkMWQxYzBlYmQ2NGFlNmJjMmQ4NzdkNWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yrcZzyD302fCpCMVicXAVbsoeiP2bJYmzqEfmCoc_JI) pr submitted now heading will look like this.

Then not required
