### ISSUE TITLE
Different Footer of Different Sections of Websites

### ISSUE THREAD

**Issue by Abbas7120** [Anjaliavv51/Retro#466]
Home Page :
![image](https://github.com/user-attachments/assets/84d3fc80-79d7-4ddf-9a49-566c070f7708)

About:
![image](https://github.com/user-attachments/assets/d7b233dd-8e85-40b8-a2b5-fffffccc4a85)

Collections:
![image](https://github.com/user-attachments/assets/4b7e5e85-87cb-4312-a39a-296aa7c44e26)

Services:
![image](https://github.com/user-attachments/assets/63cb5191-1ee9-4c23-a194-92c66ef358d8)

Contact Section:
![image](https://github.com/user-attachments/assets/1f2692b3-8595-486e-b691-b93d6b23adab)

As you see the footer secton of each page are different please assign this issue to me so that all page have same footer section 
Assign with hacktoberfest-accepted level 3 / 2 gssoc-extd

**Comment by RitikaMaha** [comment]
The footer section must be improved but just in a single particular way. 
Pl. do assign me this task

**Comment by Anjaliavv51** [comment]
@Abbas7120 go ahead.

**Comment by Abbas7120** [comment]
Ok !
