### ISSUE TITLE
Contact Us Section UI Improvement 

### ISSUE THREAD

**Issue by Abbas7120** [Anjaliavv51/Retro#467]
![image](https://github.com/user-attachments/assets/aae527fe-a07a-4d46-a59c-0ef72bb2758e)

Assign this issue to me for its best UI enhancement with gssoc-extd hacktoberfest-accepted level 3

**Comment by Dishi-Gautam** [comment]
Kindly assign me this issue. Would be glad to contribute! @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Abbas7120 aleardy assigned.
