### ISSUE TITLE
🐞[bug]: Contact page not looking good 

### ISSUE THREAD

**Issue by gyanshankar1708** [Anjaliavv51/Retro#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Contact page is not looking good.
Flex box is not added correctly.

### Expected behavior

Flex box should use correctly

### Add ScreenShots

![image](https://github.com/user-attachments/assets/233f9a14-a04e-4c90-b048-4e00e2488123)
![image](https://github.com/user-attachments/assets/cea9275f-fd65-4d6c-b589-af8d3202f577)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Pragya79645** [comment]
I would like to work upon this.

**Comment by Anjaliavv51** [comment]
@gyanshankar1708 go ahead.

**Comment by gyanshankar1708** [comment]
@Anjaliavv51, I had resolved this issue in #476, after this Ill continue #458
