### ISSUE TITLE
Issue: Overlapping Form Elements and Text in the Contact Section

### ISSUE THREAD

**Issue by JagritiChopra** [Anjaliavv51/Retro#473]
-> The contact form is duplicated, with two sets of "Your Email" and "Your Message" input fields displayed on the page.
-> The layout is broken, and there is overlapping text in both the footer section and the form, particularly around "Follow Us" and the footer menu items.
->
![Screenshot (107)](https://github.com/user-attachments/assets/42927f68-1a48-4f0d-8667-90370496bbd7)
The styling seems to cause content misalignment, and the footer section isn't adjusting properly to fit within the page's design.

Can you pls assign this to me under gssoc tag ?

**Comment by Anjaliavv51** [comment]
already assigned.
