### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by JagritiChopra** [Anjaliavv51/Retro#474]
Issue Description:
 On the "Contact Us" page, the phone number input field is not properly contained within the boundaries of the contact form. It appears to be overflowing or extending outside the designated box, which affects the visual alignment and overall design of the form.

![Screenshot (106)](https://github.com/user-attachments/assets/d78e6faf-a7ea-4aaa-b2a5-d3dfe340b20c)

can you pls assign this to me under gssoc tag ?

**Comment by Anjaliavv51** [comment]
already assigned.
