### ISSUE TITLE
✨[feature Request]: Implement Scroll-to-Top Button

### ISSUE THREAD

**Issue by samyak-aditya** [Anjaliavv51/Retro#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to enhance the user experience by adding a "Back to Top" button on the page. This button will allow users to easily navigate back to the top of the page

### Use Case

 This button will allow users to easily navigate back to the top of the page

Hey @Anjaliavv51 please assign me this task with labels "gssoc-ext" and "level1"

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@samyak-aditya pls check , i our website contains scroll to top up button.

**Comment by Anjaliavv51** [comment]
@samyak-aditya create another issue , keep contributing.
