### ISSUE TITLE
🐞[bug]: 

### ISSUE THREAD

**Issue by pranavsuriya-sr** [Anjaliavv51/Retro#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Nav to top button should be visible only when the scrolling is started in the home page. Its now visible even if the scrolling is not started.

### Expected behavior

The Nav to top button should be visible only when the scrolling is started in the home page. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by pranavsuriya-sr** [comment]
Please assign this issue to me.

**Comment by Anjaliavv51** [comment]
@pranavsuriya-sr alreqady assigned.
