### ISSUE TITLE
heading alignment in collection section

### ISSUE THREAD

**Issue by Kajalmehta29** [Anjaliavv51/Retro#485]
The heading in alignment section is not in center. It is in left side which is not nice.I want to fix this issue

Please assign this issue to me under gssoc-extd and hacktoberfest

**Comment by Anjaliavv51** [comment]
@Kajalmehta29 implement the changes.

**Comment by Kajalmehta29** [comment]
@Anjaliavv51  Please have a look

**Comment by Kajalmehta29** [comment]
Hey please add level label too @Anjaliavv51
