### ISSUE TITLE
🐞[bug]: Cart page is not responsive in small screen sizes 

### ISSUE THREAD

**Issue by srishti023** [Anjaliavv51/Retro#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The cart page is not responsive, and content not displaying properly on different screen sizes. It needs adjustments to ensure proper alignment and a more visually appealing layout across all devices.

### Expected behavior

The cart page should be fully responsive, with the contact form properly aligned, and all content displayed in an organized and visually appealing manner across all screen sizes, including mobile and tablet views.

### Add ScreenShots

https://github.com/user-attachments/assets/b210b200-1d71-42a3-add4-19673055c141

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@srishti023 go ahead.
