### ISSUE TITLE
Individual item name and price are overwritten on each new addition.

### ISSUE THREAD

**Issue by rees8** [Anjaliavv51/Retro#5]
Problem: On adding a new item, the item details are being overwritten each time in the menu.js file. 
Solution: We can make use of an array to store each item as it is being added into the cart so as to not lose the item list.

@Anjaliavv51 I would like to work on this, would be grateful if you could assign it to me.

**Comment by 1-SubhamSingh** [comment]
Hey there ,
I am interested to fix this , can you assign me this task.

**Comment by rees8** [comment]
@1-SubhamSingh I am also a contributor, this was actually an issue found by me and I wanted to ask the project owner to assign this to me.

**Comment by 1-SubhamSingh** [comment]
@rees8 Ohh !! fine

**Comment by Anjaliavv51** [comment]
@rees8 please add snippet of code in comment.

**Comment by rees8** [comment]
in menu.js:
Original code:
if (event.target.classList.contains('butt')) {
                var item = event.target.closest('.items');
                var itemName = item.querySelector('h3').textContent;
                var itemPrice = item.querySelector('p').textContent;
                alert("Item added to cart successfully");
                
                localStorage.setItem('itemName', itemName);
                localStorage.setItem('itemPrice', itemPrice);

                window.location.href = "cart.html";
            }
            
Modified version:
if (event.target.classList.contains('butt')) {
                var item = event.target.closest('.items');
                var itemName = item.querySelector('h3').textContent;
                var itemPrice = item.querySelector('p').textContent;

                alert("Item added to cart successfully");

                // Retrieve existing cart items from localStorage
                var cartItems = JSON.parse(localStorage.getItem('cartItems')) || [];

                // Add new item to the cart array
                var newItem = { name: itemName, price: itemPrice };
                cartItems.push(newItem);

                // Save updated cart back to localStorage
                localStorage.setItem('cartItems', JSON.stringify(cartItems));

                window.location.href = "cart.html";
            }

The ultimate functionality remains the same as the cart.js file is managing the process, but this small change should streamline the item addition process and is also better from the code readability point of view.

**Comment by Anjaliavv51** [comment]
@rees8 go ahead

**Comment by rees8** [comment]
Thank you. A small request though: Could you also add the hacktoberfest label to this if it is applicable? It was mentioned in the meet to remind the project owner if the tag was missing.

**Comment by Anjaliavv51** [comment]
OKAY
@rees8 please check the pin issue #11 before starting to contribute.
