### ISSUE TITLE
✨[feature Request]:  i want make image slider at bottom of site 

### ISSUE THREAD

**Issue by anish013326** [Anjaliavv51/Retro#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

An image slider enhances user engagement, efficiently showcases multiple images in limited space, provides interactive visual content, improves website aesthetics

### Use Case

Showcase projects or artwork in an organized and appealing manner.

### Benefits

Space Efficiency: Showcases multiple images in a compact space.
User Engagement: Captures attention with interactive elements.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5020a1ed-4b9d-40d3-bfa8-2fcc33340986)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@anish013326 no need of this current one looks good.
