### ISSUE TITLE
✨[feature Request]: Integrating Indian Retro Museums with Location Links

### ISSUE THREAD

**Issue by snehhhcodes** [Anjaliavv51/Retro#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The retro website currently focuses on showcasing vintage collections but does not provide any information or access to retro museums across India, which are key cultural touchpoints for enthusiasts. To address this, the website needs a feature that includes a curated list of Indian retro museums along with integrated location links that allow users to navigate to these museums via Google Maps.

### Use Case

Users visiting the retro website are often enthusiasts of vintage culture and would likely be interested in exploring physical retro museums. With the new feature, users can browse through a list of retro museums, view details of each, and easily find directions to the museum using Google Maps. This allows them to transition from the online experience of viewing vintage collections to real-world interactions by visiting historical retro museums. The website will become a one-stop resource for both virtual exploration and real-life visits.

### Benefits

By integrating retro museum locations with Google Maps, the website enhances user engagement, providing a richer and more interactive experience. This feature not only helps users discover cultural landmarks but also encourages them to visit these museums, deepening their appreciation for retro history and heritage

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@snehhhcodes go ahead.
