### ISSUE TITLE
🐞[bug]: Changing the styling of navbar and order online and collect order cards

### ISSUE THREAD

**Issue by Kritika745** [Anjaliavv51/Retro#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I think that the navbar may look much better if we work on its styling the logo is overflowing on hover and the navlinks have border very below them on hover which is not looking good.
we can decrease the length of the navbar making it sheek.
The two cards below for online order and takeaway are very larger in size which is not required as the content is very less.

### Expected behavior

the look of the website will get enhanced and user experience will be good.

### Add ScreenShots

![Screenshot 2024-10-13 200727](https://github.com/user-attachments/assets/c0fb14ef-5673-4da1-9ff4-f43ef77b5a29)
![Screenshot 2024-10-13 200740](https://github.com/user-attachments/assets/32d12377-d6ea-46b8-abe1-d2756dc8d0fc)
![Screenshot 2024-10-13 200817](https://github.com/user-attachments/assets/a5d53ecc-6241-4b58-89ce-caa3773ec062)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Kritika745 navbar changes not required , change only for those order boxes.

**Comment by Kritika745** [comment]
okay thank you. Can i make those boxes more attractive by adding some images or icons

**Comment by Kritika745** [comment]
Also I have a question if you don't mind me asking,Is there a criterion according to which you merge pr because you have over 40 pr pending ?

**Comment by Anjaliavv51** [comment]
> Also I have a question if you don't mind me asking,Is there a criterion according to which you merge pr because you have over 40 pr pending ?

No , had some work , today i had gone max to all , but still pending.

**Comment by Kritika745** [comment]
Hey @Anjaliavv51 I have solved this issue under pr #511 please review it and merge it.

**Comment by Kritika745** [comment]
hey @Anjaliavv51 please review it and merge
