### ISSUE TITLE
✨[feature Request]: 

### ISSUE THREAD

**Issue by trahulprabhu38** [Anjaliavv51/Retro#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the UI of the form can be better as the website is really well built.

<img width="254" alt="Screenshot 2024-10-02 at 2 14 49 PM" src="https://github.com/user-attachments/assets/a944ac76-6249-4e6c-9e3f-d1de0ccf9d6c">

### Use Case

this feature can beautify the whole project and increase overall UI.

### Benefits

the project can have a better UI overall.

### Add ScreenShots

<img width="254" alt="Screenshot 2024-10-02 at 2 14 49 PM" src="https://github.com/user-attachments/assets/0b050864-faab-424e-b628-e202fe59e3fd">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by trahulprabhu38** [comment]
can i start working on this?

**Comment by trahulprabhu38** [comment]
can u assign the level to this aswell?

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 give me preview screenshot of ur feature.

**Comment by trahulprabhu38** [comment]
ill work on it now

**Comment by trahulprabhu38** [comment]
this is my first time i didnt know i had to have a preview ready. ill do it in sometime

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 okay

**Comment by trahulprabhu38** [comment]
<img width="428" alt="Screenshot 2024-10-02 at 2 37 21 PM" src="https://github.com/user-attachments/assets/ed85c8dd-e5b8-4042-a2f3-0d212d1fc4ce">

the preview:

**Comment by trahulprabhu38** [comment]
<img width="391" alt="Screenshot 2024-10-02 at 2 39 23 PM" src="https://github.com/user-attachments/assets/f4f7c3ca-fb95-4e50-92db-bc34e8c3f46b">
this fits the theme better:

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 I am assigning this issue to u go ahead.

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 make sure u update that in every html pages in website.

**Comment by trahulprabhu38** [comment]
sure thank you.

**Comment by trahulprabhu38** [comment]
crosschecked other pages, it has been updated to all pages. can i create a PR?

**Comment by Anjaliavv51** [comment]
> crosschecked other pages, it has been updated to all pages. can i create a PR?

Yes please
