### ISSUE TITLE
✨[feature Request]: Add privacy-policy page to the website

### ISSUE THREAD

**Issue by Vaishh18** [Anjaliavv51/Retro#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature introduces a dedicated privacy policy page to the website, ensuring transparency and compliance with data protection regulations. The page will outline the website's practices for collecting, using, and protecting user data. It will be accessible via a link in the footer  and will provide clear information on how user privacy is maintained.

### Use Case

Key Details:

The page will include sections covering data collection, data usage, third-party sharing, cookies, and user rights.
A simple, clean UI that matches the overall design of the website.
The page will be responsive and optimized for both desktop and mobile views.

### Add ScreenShots

i will create the page similar to this matching the theme of the website 

![Screenshot 2024-10-11 210802](https://github.com/user-attachments/assets/977446be-e7d5-404a-a070-0d04482cdd6d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Vaishh18 not required.
