### ISSUE TITLE
repetition of text in footer

### ISSUE THREAD

**Issue by Kajalmehta29** [Anjaliavv51/Retro#515]
<img width="360" alt="Screenshot 2024-10-13 at 11 28 42 PM" src="https://github.com/user-attachments/assets/bf9eed46-b6c1-4a55-9b3d-a1f328b86e91">

I want to fix this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by Anjaliavv51** [comment]
@Kajalmehta29 not required
