### ISSUE TITLE
✨[feature Request]: Redirection from login page to sing up page and vice-versa and also to home page.

### ISSUE THREAD

**Issue by Thanmai44** [Anjaliavv51/Retro#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A link can be added to login page to go to sign-in page and vice-versa. I would like to work on this.

### Use Case

If a user already has an account but clicked on sing-up by mistake he can directly go to login page using this feature.

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by clownfish1805** [comment]
@Anjaliavv51 Please assign me this issue. I would like to resolve this issue.

**Comment by Thanmai44** [comment]
@Anjaliavv51 Please assign this issue to me.

**Comment by ruchikakengal** [comment]
I like to work on it , In lofin page by clicking arrow we go to signup page and similarly to signup page and for homepage also , Assign me i want to work on it

**Comment by tulikaa25** [comment]
@Anjaliavv51 i would like to work on this issue and improve the user experience.Please assign it to me.
