### ISSUE TITLE
✨[feature Request]:  Show Password Feature

### ISSUE THREAD

**Issue by saras-69** [Anjaliavv51/Retro#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of a "Show Password" feature in the login and signup forms. This feature will include an eye icon that users can click to toggle the visibility of their password inputs, making it easier to verify their entries.

### Use Case

This feature would enhance user experience by allowing users to confirm their password inputs before submitting the form. In scenarios where users are entering complex passwords, being able to see their input can significantly reduce the chances of errors and frustration during login or registration.

### Benefits

Implementing this feature would improve user satisfaction and decrease the number of failed login attempts due to mistyped passwords. It can lead to a smoother onboarding experience for new users and overall increased usability of the application.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@saras-69 go ahead!
