### ISSUE TITLE
✨[feature Request]: Improving Functionality of submit button on contact us page

### ISSUE THREAD

**Issue by Devanshu1603** [Anjaliavv51/Retro#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On clicking submit button , an error is showing . i want that on clicking submit button an alert must pop out stating that your details has been sent successfully to let user know whether their response has been submitted or not , and text field should get cleared .

### Use Case

Inchancing UI of website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Devanshu1603** [comment]
@Anjaliavv51  please assign me this issue under gssoc-ext , hacktober fest and with appropriate levels. will be happy to contribute.

**Comment by Anjaliavv51** [comment]
@Devanshu1603 give preview of the video

**Comment by Devanshu1603** [comment]
> @Devanshu1603 give preview of the video

@Anjaliavv51  what preview i have to submit , or error or of the improvement i would make.

**Comment by Anjaliavv51** [comment]
> > @Devanshu1603 give preview of the video
> 
> @Anjaliavv51 what preview i have to submit , of error or of the improvement i would make.

improvement

**Comment by Devanshu1603** [comment]
@Anjaliavv51  i haven't made the improvement yet , was waiting for you to assign me this issue

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 i haven't made the improvement yet , was waiting for you to assign me this issue. should i make the improvement and provide you the video.

yes

**Comment by Devanshu1603** [comment]
@Anjaliavv51  ok doing it in a while

**Comment by Devanshu1603** [comment]
@Anjaliavv51  following is the improvement i will make :- 

https://github.com/user-attachments/assets/df355a40-9a95-4377-a7b8-0a8a9cb1800f

**Comment by Devanshu1603** [comment]
@Anjaliavv51 please assign me this issue .

**Comment by Anjaliavv51** [comment]
@Devanshu1603 go ahead.
