### ISSUE TITLE
🐞[bug]: 

### ISSUE THREAD

**Issue by trahulprabhu38** [Anjaliavv51/Retro#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the home page link is broken, If u can assign this to me ill fix it.

### Expected behavior

this was the link to the home page and its broken. Becasue of this the home page is not accessible.

### Add ScreenShots

<img width="747" alt="Screenshot 2024-10-02 at 2 19 17 PM" src="https://github.com/user-attachments/assets/9e8e5ee8-eba3-48f2-b4f6-ef832ce8d5f8">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
It is being fixed , rise any other issue @T-Rahul-prabhu-38
