### ISSUE TITLE
🐞[bug]:  contact us is not aligned

### ISSUE THREAD

**Issue by ChauhanAyush04** [Anjaliavv51/Retro#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

your email and your message is not aligned in contact us.
![Screenshot 2024-10-14 144024](https://github.com/user-attachments/assets/348d3a9b-f690-429f-b8b1-945fb9d0dcb1)

### Expected behavior

it should be aligned.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by ChauhanAyush04** [comment]
@Anjaliavv51

**Comment by Anjaliavv51** [comment]
Already assigned.
