### ISSUE TITLE
✨[feature Request]: Signup page UI does not matches with the Login page UI

### ISSUE THREAD

**Issue by amitroy-thedev** [Anjaliavv51/Retro#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/3c1c9a2e-8fcd-4c45-84ed-cd83b9c9e829)
![image](https://github.com/user-attachments/assets/31809956-a768-4bae-ac35-8cc273313c5d)
Signup page UI does not matches with the login page UI
@Anjaliavv51 assign this to me i want to fix that

### Use Case

Similar UI makes the user feel connected with the content

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by mudit0204** [comment]
please assign me this @Anjaliavv51!!

**Comment by vaiidehisb** [comment]
Here I am with the blend of designing and technecial skills. this will be a great apportunity to contribute as to this task. being a UI/UX specialist and a Coder. I am contribute in this.

**Comment by Anjaliavv51** [comment]
@vaiidehisb then please create an issue of your own.

**Comment by Anjaliavv51** [comment]
@amitroy-thedev if u r active please create PR and mention me

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 okay
