### ISSUE TITLE
🐞[bug]: Fix in "Login page validation" and improvement in UI

### ISSUE THREAD

**Issue by clownfish1805** [Anjaliavv51/Retro#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Field Validation:** 
{**Signup page gets an email id so login should also use email id rather than user name**}
1. Ensure the "email" and "password" fields are not left empty before submission.
2. Validate the "Email" field to ensure the input follows a proper email format (e.g., name@example.com).

**Improvement in UI:**
To give a proper improved ui on the left side of the login page which aligns with the websites rules and guidelines.

### Expected behavior

**Field Validation:**
The "Email" and "Password" fields must be filled before submission. If empty, **an error message will prompt the user to complete them.**
The "Email" field must follow a valid format (e.g., name@example.com). If not, **an error message will indicate the issue.**

**UI Improvement:**
The left side of the login page will feature a **visually appealing design** that aligns with the website's branding and guidelines, enhancing user engagement and experience.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5cd98a90-221f-451a-9607-78d7a8ee1d25)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by clownfish1805** [comment]
@Anjaliavv51 Please assign me this issue with level labels.

**Comment by Shalinis19137** [comment]
I would like to work on issue #55 in the Login page validation and improving in UI repository. Could you please assign it to me? Thank you!
