### ISSUE TITLE
Enhance the section above footer to center.

### ISSUE THREAD

**Issue by RohanShrivastava08** [Anjaliavv51/Retro#554]
![Screenshot (495)](https://github.com/user-attachments/assets/dbcfbef7-8edf-4f01-abfe-9d68be2c1900)

As, the 'Free Delivery' part till - 'Google Play & App Store' are placed at left.
So, I want to make it Center aligned. I tried it and it looked well and aligned well with the website !!
Kindly, assign me this, so that I make this changes to make website more classy !

**Comment by Anjaliavv51** [comment]
> ![Screenshot (495)](https://private-user-images.githubusercontent.com/94133270/376322419-dbcfbef7-8edf-4f01-abfe-9d68be2c1900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjQ2MTIsIm5iZiI6MTcyODkyNDMxMiwicGF0aCI6Ii85NDEzMzI3MC8zNzYzMjI0MTktZGJjZmJlZjctOGVkZi00ZjAxLWFiZmUtOWQ2OGJlMmMxOTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE2NDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNDA0ZTM0YzYzMmU5MGVjNzMwNmY0MmRjMmYwZTEyNmQyNTBmYTllMjMyZmQ1YjAzY2FhMGI4ZWIxYmZkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mvly8bNWhz6QfIg-AtAq7jxkjJ2joSgwcT9KpCK3VQQ)
> 
> As, the 'Free Delivery' part till - 'Google Play & App Store' are placed at left. So, I want to make it Center aligned. I tried it and it looked well and aligned well with the website !! Kindly, assign me this, so that I make this changes to make website more classy !

just show preview screenshoot of ur changes.

**Comment by RohanShrivastava08** [comment]
![Screenshot (500)](https://github.com/user-attachments/assets/98212e8b-2f81-4da8-b4b6-d0a4bcec26e5)

Have a look, I aligned it well at center.

**Comment by Anjaliavv51** [comment]
> ![Screenshot (500)](https://private-user-images.githubusercontent.com/94133270/376331367-98212e8b-2f81-4da8-b4b6-d0a4bcec26e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODc3MTMsIm5iZiI6MTcyODk4NzQxMywicGF0aCI6Ii85NDEzMzI3MC8zNzYzMzEzNjctOTgyMTJlOGItMmY4MS00ZGE4LWI0YjYtZDBhNGJjZWMyNmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDEwMTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTZjN2EyZTU5YWVjMTA5NDBjNWNjMmNmNDljZjYyNDE3ZDRjOTRlNjU0ZDQ1ZmE2YTA5YzhiMzBlMGFhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9U4Lj7JXtG0j3uBawvdpnIhRTOq5hy1FsWSaVLq0imk)
> 
> Have a look, I aligned it well at center.

i think it looks good by aliging at left , not required, please create some other issue.
