### ISSUE TITLE
✨[feature Request]: to make the chat section more colorful and attractive.

### ISSUE THREAD

**Issue by Rish6392** [Anjaliavv51/Retro#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to make it colorful.

### Use Case

it will make it more attractive.

### Benefits

it will look amazing and attractive  for the users.

### Add ScreenShots

![Screenshot 2024-10-14 230124](https://github.com/user-attachments/assets/fa9f5118-2f38-48ab-9bd4-149e64ee99b4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Rish6392** [comment]
#561 please assign this issue to me .

**Comment by Anjaliavv51** [comment]
@Rish6392 go ahead.

**Comment by Rish6392** [comment]
can i make my own chatbot. would you please provide me discription for the chatbot.

**Comment by Anjaliavv51** [comment]
> can i make my own chatbot. would you please provide me discription for the chatbot.

No
