### ISSUE TITLE
🐞[bug]: No proper alignment of footer of the About Section

### ISSUE THREAD

**Issue by Roshn1** [Anjaliavv51/Retro#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is so much gap in between the contents of contact like your email,your message, send message . Also the our pages is not properly aligned to the centre , it is more shifted towards right which is not looking nice.

### Expected behavior

Hi , I came across this issue. I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d175e3fa-8331-4ffc-b452-5b8693a18bfe)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Roshn1 if possible make the footer of the html page similar to index.html but don't skip the train animation part
