### ISSUE TITLE
🐞[bug]: Poorly aligned Contact Us in Footer section of Services

### ISSUE THREAD

**Issue by Roshn1** [Anjaliavv51/Retro#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/3c55c1de-c4e2-478d-8ed5-2c9d20137e8f)
the width of all the three components i.e your email ,your message , send message is not properly aligned 

### Expected behavior

Hi , I came across this issue .I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Arghya-Chakraborty0812** [comment]
Please can you assign this issue to me

**Comment by Anjaliavv51** [comment]
@Roshn1 implement it to all html pages.
