### ISSUE TITLE
✨[feature Request]: add translator feature 

### ISSUE THREAD

**Issue by HimangshuSharma01** [Anjaliavv51/Retro#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Is your feature request related to a problem? Please describe.**
ADD A TRANSLATOR IN THE WEBSITE TO MAKE THE USER EXPERIENCE GOOD IT WILL BE HELPFUL FOR THE PEOPLE WHO ARE MORE COMFORTABLE TO THEIR NATIVE LANGUAGES

**Describe the solution you'd like**
![Screenshot 2024-10-14 110922](https://github.com/user-attachments/assets/0a75d2ce-ec82-49ac-b29f-7e9f409cb887)

**Additional context**
I can work in this

### Use Case

ADD A TRANSLATOR IN THE WEBSITE TO MAKE THE USER EXPERIENCE GOOD IT WILL BE HELPFUL FOR THE PEOPLE WHO ARE MORE COMFORTABLE TO THEIR NATIVE LANGUAGES

### Add ScreenShots

![Screenshot 2024-10-14 110922](https://github.com/user-attachments/assets/0a75d2ce-ec82-49ac-b29f-7e9f409cb887)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@HS202022 go ahead.

**Comment by HimangshuSharma01** [comment]
> @HS202022 go ahead.

Assign me I will do it with in 5 to 10 mins just assign and give level 2 please @Anjaliavv51
