### ISSUE TITLE
🐞[bug]: Navbar overlaps with the contents while scrolling down

### ISSUE THREAD

**Issue by Annapoornaaradhya** [Anjaliavv51/Retro#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar text overlaps with the footer content when scrolled until last.

### Expected behavior

I would like to add a transparent background matching to the current design to overcome the problem.
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/552f087b-2b5e-4315-9925-1bcdbfb1b2c3)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Annapoornaaradhya** [comment]
@Anjaliavv51 please do assign me this issue

**Comment by Pratikpawar13** [comment]
@Anjaliavv51 I would like to solve the issue. 
Please assign me this issue to solve it.

**Comment by Anjaliavv51** [comment]
@Annapoornaaradhya it is already assigned.
