### ISSUE TITLE
Improve Button Design for "Order Online" and "Take out Order" on Frontend

### ISSUE THREAD

**Issue by amankumarcu** [Anjaliavv51/Retro#6]
<img width="1435" alt="Screenshot 2024-10-01 at 6 46 33 PM" src="https://github.com/user-attachments/assets/91f90039-1b87-48b1-9bdb-3f325c7a6d59">

The current design of the "Order Online" and "Take out Order" buttons lacks a modern and visually appealing style. They appear outdated and are not aligned with the overall sleek and professional look of the page. The buttons require improvements in the following areas:

1. Typography: The current font does not match the elegance of the other texts on the page.
2. Padding & Sizing: The buttons could be more prominent with better padding and sizing to make them more accessible and user-friendly.
3. Colors: The red color scheme should be enhanced with a gradient, shadow, or hover effect to make the buttons more interactive 4. and attractive.
Border Styling: Consider softening or adjusting the border to blend better with the page background while maintaining contrast.

**Comment by amankumarcu** [comment]
@Anjaliavv51 assign me this issue

**Comment by Anjaliavv51** [comment]
@amankumarcu please give preview video of your idea button.

**Comment by amankumarcu** [comment]
<video src="https://github.com/user-attachments/assets/ae18db47-260f-469b-bab8-9eb3ace547dc"></video>
@Anjaliavv51 preview video of my idea button.

**Comment by Anjaliavv51** [comment]
@amankumarcu goahead
