### ISSUE TITLE
🐞[bug]: Nav bar is not same for all pages

### ISSUE THREAD

**Issue by Pratikpawar13** [Anjaliavv51/Retro#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Nav bar is not same for all pages.
It will look like unprofessional 

### Expected behavior

Nav bar should be same for all the pages ,
with fixed position

### Add ScreenShots

**Home page nav bar**
![Screenshot 2024-10-02 151519](https://github.com/user-attachments/assets/47ee980f-b721-4276-904e-7deab3d44233)

**Contact us nav bar**
![Screenshot 2024-10-02 151538](https://github.com/user-attachments/assets/ba7b0124-bd24-4c23-bfa2-cb27eab50851)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Pratikpawar13** [comment]
@Anjaliavv51 I want to solve this issue.
Please assign me this issue to solve that problem.

**Comment by Anjaliavv51** [comment]
@Pratikpawar13 please wait for a while coz UI of navbar is going to change something.

**Comment by Anjaliavv51** [comment]
I will assign this issue to u after few hours.

**Comment by ruchikakengal** [comment]
I would like to work on navbar and add additinal options in navbar

**Comment by vararaghu002** [comment]
Interested to work on this project, pls assign to me.

**Comment by rohitsharma2610** [comment]
hey, i have excellent command in front-end development, so i want to work on this and want to make this site beautiful.

**Comment by Anjaliavv51** [comment]
> hey, i have excellent command in front-end development, so i want to work on this and want to make this site beautiful.

@rohitsharma2610 please raise a new issue
