### ISSUE TITLE
🐞[bug]: Signup page looks wierd

### ISSUE THREAD

**Issue by satyamra1** [Anjaliavv51/Retro#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Signup page CSS and alignment looks improper. Signup page generally looks similar to login page.

### Expected behavior

Their should be proper gap between signup form and card

### Add ScreenShots

signup - 
![image](https://github.com/user-attachments/assets/e3718ef0-95fe-4bff-b9b6-38ef24fa79e9)

Login page:
![image](https://github.com/user-attachments/assets/9b0d7ea0-fd8f-4778-a385-9dc3ca24edf8)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @KrishPatel1205

**Comment by satyamra1** [comment]
Its have been 2 days , please assign this task to me

**Comment by Anjaliavv51** [comment]
@satyamra1 it's already been assigned.

**Comment by satyamra1** [comment]
> @satyamra1 it's already been assigned.

When you assigned me? 

it stills look same : 
![image](https://github.com/user-attachments/assets/bd2b7c5a-173f-465a-b1f2-c0063805c53b)
