### ISSUE TITLE
🐞[bug]: make navbar position fix

### ISSUE THREAD

**Issue by RiddhiM170904** [Anjaliavv51/Retro#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Navigation bar to be positioned at top. Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.

### Expected behavior

The navigation bar to be settled at the top of the page. but it is moving when scrolled down.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7d52c9a3-3749-4b9a-a219-8946bfd1a305)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
It is already on the way to be fixed please create some other issue.
