### ISSUE TITLE
✨[feature Request]: Improve the UI of Home Page

### ISSUE THREAD

**Issue by Sudhanshu248** [Anjaliavv51/Retro#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the front of home page the picture and sign up section is not properly fixed. Through which website not looks good.

I can improve it.

@Anjaliavv51  Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

### Use Case

I would like to enhance the UI of Home Page.

### Benefits

The Home page looks good, Sign up section will also looks good.

### Add ScreenShots

![Screenshot 2024-10-16 202957](https://github.com/user-attachments/assets/fcb0c524-d6a6-4112-b355-d0ac3b0573fd)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Sudhanshu248** [comment]
@Anjaliavv51 Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Anjaliavv51** [comment]
@Sudhanshu248 their is no such misalignment in our repo output , please check in through the below link.

https://rococo-mooncake-0d89f7.netlify.app/
