### ISSUE TITLE
🐞[bug]: Images remained unloaded

### ISSUE THREAD

**Issue by RiddhiM170904** [Anjaliavv51/Retro#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Images remained unloaded and only photo icon was being displayed. Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.

### Expected behavior

there would be images over there.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/46c6f9fb-6015-4e0f-adbd-526cbcb34106)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@RiddhiM170904 it already been assigned.
