### ISSUE TITLE
Customer opinions should be in swipe format

### ISSUE THREAD

**Issue by Kajalmehta29** [Anjaliavv51/Retro#639]
<img width="991" alt="Screenshot 2024-10-18 at 12 21 05 AM" src="https://github.com/user-attachments/assets/91af41f5-ca84-48bf-9e76-c527635f4e75">

Instead of customer opinions like this we can make it in swipe format and also add more reviews accordingly without occupying much space. 
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by Anjaliavv51** [comment]
@Kajalmehta29 go ahead.

**Comment by Kajalmehta29** [comment]
@Anjaliavv51  Please merge this PR. I have to work on another issue for your site.
Thankyou.

**Comment by Kajalmehta29** [comment]
@Anjaliavv51  Please have a look and merge this. Also, provide level 2 if possible.
