### ISSUE TITLE
alignment of cart icon

### ISSUE THREAD

**Issue by Kajalmehta29** [Anjaliavv51/Retro#641]
<img width="1378" alt="Screenshot 2024-10-18 at 12 26 05 AM" src="https://github.com/user-attachments/assets/7a9f0735-3892-4841-829c-5f3770384199">

Cart icon should be on the top right side of the nav bar.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by Aksshhada** [comment]
I am interested to work on this issue

**Comment by Raj-banerjee25** [comment]
Can you assign this issue this to me

**Comment by Anjaliavv51** [comment]
@Kajalmehta29 go ahead
