### ISSUE TITLE
✨[feature Request]: Adding multi language support system✨

### ISSUE THREAD

**Issue by Varsha-1605** [Anjaliavv51/Retro#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to this functionality so that most of the users can use this website for them in their native language.

@Anjaliavv51 I would love to work on it, could you please assign this task to me?

### Use Case

Easier for ppl to understand content in their native language.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Varsha-1605** [comment]
@Anjaliavv51 Kindly have a look at this issue!!!

**Comment by Anjaliavv51** [comment]
it is already inmplemented.
