### ISSUE TITLE
🐞[bug]: Registration popup for mobile

### ISSUE THREAD

**Issue by jainaryan04** [Anjaliavv51/Retro#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the layout and styling of the registration popup needs to be updated for mobile view @Anjaliavv51 
![image](https://github.com/user-attachments/assets/30d54517-2a97-41ec-bdf1-299593011aca)

### Expected behavior

reduce width and increase height of the div for mobile. 
put the image on top and text below it

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@jainaryan04 go ahead I will add level label to PR

**Comment by jainaryan04** [comment]
Please merge @Anjaliavv51
