### ISSUE TITLE
📝[documentation Update]: README.md file

### ISSUE THREAD

**Issue by dharmesh191312** [Anjaliavv51/Retro#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Get Started Section can be a bit more clear and understandable with enhanced visual appeal.
No Contribution Points Section for GSSoC 
No Key Features Section
No Contact Section

### Suggested Change

Making Get Started Section more visually appealing and more understandable.
Adding the Contribution Points Section for GSSoC
Adding Key Features Section
Adding Contact Section

### Rationale

It will be a good enhancement for README.md

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@dharmesh191312 send preview of ur changes.
