### ISSUE TITLE
📝[documentation Update]:  Missing CONTRIBUTING.md File

### ISSUE THREAD

**Issue by archanasingh11** [Anjaliavv51/Retro#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

**Description:**  
The repository is missing a `CONTRIBUTING.md` file, which is essential for guiding contributors on how to properly contribute to the project. This file typically outlines important guidelines, such as how to report issues, create pull requests, code style conventions, and other contribution practices.

**Expected Outcome:**  
Having a clear `CONTRIBUTING.md` will help maintain a consistent contribution workflow and make it easier for both new and experienced contributors to participate in the project.

### Suggested Change

 Having a clear `CONTRIBUTING.md` will help maintain a consistent contribution workflow and make it easier for both new and experienced contributors to participate in the project.

Hey @Anjaliavv51 please assign me this task with label "gssoc-ext", "hacktoberfest-accepted"  and "level1".

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@archanasingh11 go ahead.

**Comment by archanasingh11** [comment]
Hey @Anjaliavv51 I have raised the PR
Thanks

**Comment by archanasingh11** [comment]
Please @Anjaliavv51  assign me the label "level1" or else my contribution wont be counted
