### ISSUE TITLE
🐞[bug]: Found unexpected enlarging of the Navbar element Retro in dark mode

### ISSUE THREAD

**Issue by harjasae2001** [Anjaliavv51/Retro#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When in dark mode on hovering on the Retro element in the navbar it unexpectedly grow in size and also the colour is not visible to read

### Expected behavior

There should be no enlargement of the text Retro and the colour should change on hovering

### Add ScreenShots

![{B4FA9D5E-4E8B-4377-A2E6-B6075123A97A}](https://github.com/user-attachments/assets/cb22c0d5-97ae-4b9f-81be-8f49869642da)

![{DA660487-A153-4FCF-8F33-7991E5551DDC}](https://github.com/user-attachments/assets/8ad32700-1bc4-4ea5-98fb-e6ba3364d2db)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by harjasae2001** [comment]
pls assign me this isssue

**Comment by Anjaliavv51** [comment]
@harjasae2001 that is the feature it self

**Comment by harjasae2001** [comment]
But what about the color change
