### ISSUE TITLE
🐞[bug]: There is an issue with the Navbar's dark mode functionality that requires improvement.

### ISSUE THREAD

**Issue by ananydev** [Anjaliavv51/Retro#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current dark mode for the Navbar has some problems, like the colors not looking right or the background not showing properly, which makes it harder for users to navigate the website.

### Expected behavior

Fix the colors of the Navbar in dark mode so that everything is easy to see. Make sure the background and text are clear and visible.

Priority: Medium

### Add ScreenShots

![image](https://github.com/user-attachments/assets/48d53754-0840-4031-a2bb-aba3024f1680)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@ananydev it already assigned and going to be rectified

**Comment by ananydev** [comment]
Hi! 👋 I'm really interested in contributing to this project, especially to fix the dark mode issue in the Navbar. Please assign it to me at a medium level of priority. I look forward to working on this! 😊

**Comment by ananydev** [comment]
Kindly assign it to me, and it'll be solved by today

**Comment by Anjaliavv51** [comment]
> @ananydev it already assigned and going to be rectified

Read this , it is already assigned to other people
