### ISSUE TITLE
🐞[bug]: Adjust Scroll to Top Button Size to Match Chatbot Icon

### ISSUE THREAD

**Issue by sezallagwal** [Anjaliavv51/Retro#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current "scroll to top" button appears to be smaller than the chatbot icon. To improve consistency and UI balance, the "scroll to top" button should be resized to match the size of the chatbot icon.

### Expected behavior

The "scroll to top" button should have the same size (width and height) as the chatbot icon.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/943424eb-1913-40ba-9f77-b8a7c9263b04)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@sezallagwal it's not required
