### ISSUE TITLE
✨[feature Request]: Add hover effects to FAQ section

### ISSUE THREAD

**Issue by sezallagwal** [Anjaliavv51/Retro#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhance the user experience by adding smooth animations to the FAQ section. The animations should improve the interactivity and visual appeal when a user expands or collapses a question.

### Use Case

Apply a smooth sliding animation when expanding and collapsing the FAQ items.
The transition should be fast enough to keep the interaction responsive but slow enough for a smooth effect (e.g., 0.3s - 0.5s duration).
Icon Animation:
Rotate or change the icon next to each question when expanded and revert back when collapsed.
The icon animation should synchronize with the expand/collapse animation.

### Add ScreenShots

https://github.com/user-attachments/assets/db229dc9-f6bc-4795-9d77-52e74aecf957

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@sezallagwal go ahead create PR I will add level label to the PR
