### ISSUE TITLE
Navbar is missing is Login Page.

### ISSUE THREAD

**Issue by Ibrangrd** [Anjaliavv51/Retro#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Navbar is missing is Login Page. 

### Suggested Change

Add navbar in login page.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Ibrangrd** [comment]
Ok , i am waiting for your response.

**Comment by Anjaliavv51** [comment]
@Ibrangrd not required

**Comment by Ibrangrd** [comment]
ok
