### ISSUE TITLE
Add newsletter signup 

### ISSUE THREAD

**Issue by kartikey369-ind** [Anjaliavv51/Retro#74]
How about adding a newsletter signup feature in our page which allows user to get our updates...

**Comment by Anjaliavv51** [comment]
@kartikey369-ind please add preview video of ur idea.

**Comment by kartikey369-ind** [comment]
![Screenshot_20241002-164918.png](https://github.com/user-attachments/assets/aea7246b-bad2-475d-849f-1f0d0455ddbc)

**Comment by Anjaliavv51** [comment]
@kartikey369-ind we already have that in our webpage in footer section.
