### ISSUE TITLE
Feature Request: Implement Customer Reviews & Ratings Section

### ISSUE THREAD

**Issue by sezallagwal** [Anjaliavv51/Retro#762]
## Description
We need to add a customer reviews and ratings section for each product or service. This feature will allow users to leave feedback on products, enhancing trust and transparency for future customers. Reviews will also help other users make informed decisions before purchasing.

## Requirements
1. **Review Form**
   - Add a form under each product or service page where users can submit their review.
   - The form should include:
     - A text area for the user to write their review.
     - A star rating system (e.g., 1–5 stars).
     - A submit button to post the review.

2. **Display Reviews**
   - Display user reviews in a list under the product or service page.
   - Each review should include:
     - The user’s name or username.
     - The star rating.
     - The text of the review.
     - The date the review was posted.

5. **Design**
   - The reviews section should match the overall theme and design of the website.
   - Display reviews in a visually clean and readable layout.
   - 
please assign this to me under `gssoc-ext` and `hacktoberfest` @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@sezallagwal go ahead and level will be added to the PR
