### ISSUE TITLE
Adding home page button on Signup and Login page

### ISSUE THREAD

**Issue by Kcode15** [Anjaliavv51/Retro#8]
Including a home button on the sign-up and login pages will improve the user experience by providing easier navigation.

![image](https://github.com/user-attachments/assets/522611a7-3df6-494d-adef-e59009734c9c)
![image](https://github.com/user-attachments/assets/de80c91c-a898-48fd-837d-ce45cf712d05)

**Comment by Kcode15** [comment]
please assign me this issue

**Comment by Anjaliavv51** [comment]
@Kcode15

**Comment by rishiakkala** [comment]
Hey @Anjaliavv51 , I want work on this can you assign this to me?

**Comment by clownfish1805** [comment]
@Anjaliavv51 I would like to work on this issue.
**My plan:**
To add **header and footer** for **Login and signup page** that aligns with the Retro project home page.

Please assign me this issue.

**Comment by Anjaliavv51** [comment]
@clownfish1805 first come first serve so please create any other issue.
