### ISSUE TITLE
🐞[bug]: Icon Overlap and Alphabet Input Allowed in Phone Number Field

### ISSUE THREAD

**Issue by rahulgithub-web** [Anjaliavv51/Retro#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the **contact form**, there are two issues:

1. The phone number field allows users to enter alphabets instead of restricting the input to only numbers.

2.  When typing into any of the form fields, the input text overlaps with the icons placed inside the fields, causing usability issues.

### Expected behavior

1. Phone Number Field: The phone number field should restrict input to only numeric values, preventing users from entering alphabets or special characters.

2. Icon Alignment: When a user clicks on a form field and begins typing, the text should not overlap the icon. The text input should start after the icon, keeping the icon properly aligned and separate from the input text.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/dc21e298-fdac-48e4-aab4-4c7263bb3000)

**Current behavior (Icon Overlap):**
_> The input text overlaps with the icon in the email and phone fields._
![image](https://github.com/user-attachments/assets/5bad73bb-bd3e-4eb5-b3a3-0c75b9aa7f7c)

**Phone Number Issue:**
_Alphabets are allowed in the phone number field._
![image](https://github.com/user-attachments/assets/81547cd4-3b9f-4c4d-8ab7-bf603548d8ef)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by rahulgithub-web** [comment]
@pand-coder @rees8 @amankumarcu @archanasingh11. Please assign this task to me

**Comment by rahulgithub-web** [comment]
@archanasingh11 @pand-coder  @rees8 @amankumarcu @Anjaliavv51 
I have fixed the bug. Shall you please add the **hacktoberfest** label

**Comment by Anjaliavv51** [comment]
> @archanasingh11 @pand-coder @rees8 @amankumarcu @Anjaliavv51 I have fixed the bug. Shall you please add the **hacktoberfest** label

I am only the maintainer here.

**Comment by rahulgithub-web** [comment]
@Anjaliavv51 I understand, thank you for the clarification and your time. I appreciate your assistance and will await any further steps.
