### ISSUE TITLE
creating a complain box

### ISSUE THREAD

**Issue by sejals23** [Anjaliavv51/Retro#84]
A complaint box on a website allows users to provide feedback, report issues, or express concerns directly to the site administrators. This feature ensures that customers or visitors can easily communicate problems they encounter, whether related to products, services, or website functionality.
To enhance usability, options like category selection (e.g., technical issue, service complaint, product concern) and file attachments (for screenshots or documents) can be added.
This feature not only improves customer satisfaction by showing that their feedback is valued, but it also helps businesses identify areas for improvement and maintain high standards of service.

**Comment by Anjaliavv51** [comment]
@sejals23 no need.
