### ISSUE TITLE
✨[feature Request]: attractive header

### ISSUE THREAD

**Issue by dagiz6** [Anjaliavv51/Retro#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can make the header more attractive , please assign me  this task

### Use Case

the header is a little bit dim, I will make it better

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@dagiz6 give preview video of your feature.

**Comment by dagiz6** [comment]
https://github.com/user-attachments/assets/f0d34977-8441-4f3d-a070-5a674e0be042

like this

**Comment by Anjaliavv51** [comment]
@dagiz6 navbar us going to updated sp please create some other issue and more over please update ur branch.
