### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by karu345** [Anjaliavv51/Retro#9]
![Screenshot 2024-10-01 190256](https://github.com/user-attachments/assets/71239a32-7610-4afe-b391-46226fac8a70)
can do responsive design.

**Comment by karu345** [comment]
Please assign this to me.

**Comment by Anjaliavv51** [comment]
Go ahead.

**Comment by Anjaliavv51** [comment]
@karu345

**Comment by karu345** [comment]
okay thankyou

**Comment by karu345** [comment]
one more request can you please add hacktober fest if possible.

**Comment by ruchikakengal** [comment]
I would like to work on it, assign me

**Comment by Anjaliavv51** [comment]
> I would like to work on it, assign me

Sure

**Comment by Akanshaku** [comment]
I would like to work on it pls assign me this.
request you to add hacktoberfest and labels.

Record

1. I have read the Contributing Guidelines
 2.I'm a GSSOC'24 contributor
 3.I have starred the repository

**Comment by Codersweta7** [comment]
@Anjaliavv51  
hii i want to work on this repository to make it responsive and with better user interface please assign this to me.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 hii i want to work on this repository to make it responsive and with better user interface please assign this to me.

directly create PR.
