### ISSUE TITLE
✨[feature Request]: Make the footer design on contact page same as the home page.

### ISSUE THREAD

**Issue by Orca-63** [Anjaliavv51/Retro#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The footer design on the home page and the contact page currently differ, leading to an inconsistent user experience. I would like to design the footer of the contact page similar to the home page for a better layout of the website.

### Use Case

This feature would enhance the use of the project by creating a more cohesive and intuitive user experience.

### Add ScreenShots

Footer of the home page : 
![Screenshot 2024-10-02 201245](https://github.com/user-attachments/assets/d3fe4e93-404a-43da-98e7-84a516a4c92e)

Footer of the contact page : 
![Screenshot 2024-10-02 201052](https://github.com/user-attachments/assets/70791e8e-324d-43d0-8ddc-0183ae6dd5de)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@Orca-63 go ahead.
